### ISSUE TITLE
Grabar cómo crear un grupo de contactos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#1]
Crear un vídeo en el que se muestre cómo se crea un grupo (sin añadir usuarios, sólo crear el grupo dándole un nombre) de contactos en el correo electrónico

**Comment by albaag20** [comment]
video grabado https://drive.google.com/open?id=0B7VbTuFV9GGEX2J6M0kzSTMzRjQ

**Comment by profeIAP** [comment]
Perfecto Alba pero te voy a abrir la tarea sólo para asegurarme que ocultas el enlace que has puesto en el comentario anterior :)

**Comment by profeIAP** [comment]
Perfecto, gracias
