### ISSUE TITLE
Grabar cómo añadir recursos a la biblioteca multimedia de PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#10]
Crear un vídeo en el que se muestre cómo se pueden añadir distintos recursos multimedia (vídeos, imágenes, sonido, ...) en PiTiVi

**Comment by alexandrabr00** [comment]
video grabado https://drive.google.com/open?id=0BwVcIj8YsvWwWC1QQkI1dHFjdGM

**Comment by profeIAP** [comment]
La verdad es que te ha quedado chulo peeerrrooo:
1. Recomendaría importar todas las imágenes de una sola vez (resulta tedioso hacerlo una a una ¿no te parece? ;) )
1. Yo añadiría algún vídeo y no sólo imágenes
1. El objetivo es importar recursos **distintos** a la biblioteca multimedia (no es necesario que los incluyas en la línea de tiempo)

Por lo demás te ha quedado bastante bien :)

**NOTA:** el enlace del comentario anterior hay que ocultarlo que queda "feo" ;)

**Comment by profeIAP** [comment]
Recuerda ocultar el enlace

**Comment by alexandrabr00** [comment]
[video nuevo](https://drive.google.com/open?id=0BwVcIj8YsvWwZHVjTDdoV1BSdnM)

**Comment by profeIAP** [comment]
Suficiente Alexa, no me "tortures" más con Bob Esponja, please..

El objetivo era añadir recursos a la biblioteca multimedia, no enseñar a añadirlos a la línea de tiempo.

Céntrate en lo primero por lo que agradecería que, usando PiTiVi (para evitar tener que grabalor nuevamente), cortes toda la parte que hay tras el segundo 20 (o 21).

La **idea** es que aparezcan los ficheros importados en la biblioteca, quita cuando empiezas a arrastrar a la línea de tiempo ;)

**Comment by alexandrabr00** [comment]
[video](https://drive.google.com/open?id=0BwVcIj8YsvWwYW9ITGNsMGtZRW8)

**Comment by profeIAP** [comment]
Vuelves a hacer lo mismo, no lo entiendo (y sospecho que tú, tampoco)
Creo que lo más "operativo" será que me preguntes en clase y así nos aseguramos que lo entienes y no hacemos trabajo en balde ¿te parece?

**Comment by alexandrabr00** [comment]
ya esta listo el [video](https://drive.google.com/open?id=0BwVcIj8YsvWwWm1fQUN2Zldfc00)

**Comment by profeIAP** [comment]
Ahora sí... ¡Perfecto Alexa, muchas gracias!
Buen trabajo, se ve muy clarito y bien, ¡enhorabuena!
