### ISSUE TITLE
Narrar cómo recortar un fragmento de una imagen usando Gimp 

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#100]
Describir el proceso seguido en el vídeo de la tarea #99

**Comment by elenashp** [comment]
Aquí tienes [el audio](https://drive.google.com/file/d/0B836udDJlFJjbWdIUGpWYVlqNnM/view?usp=sharing)

**Comment by profeIAP** [comment]
Se corta de forma abrupta al final (vas muy "forzada" narrando porque imagino que te da algo de "corte"... nunca mejor dicho teniendo en cuenta la tarea 😜) pero como también tienes asignada la tarea de edición lo dejo en tus manos para ver qué tal queda el "producto" final.

Sigue así Elena, que lo estás haciendo muy bien
