### ISSUE TITLE
Editar vídeo cómo recortar un fragmento de una imagen usando Gimp

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#101]
Usando PiTiVi, editar el vídeo de la tarea #99 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by elenashp** [comment]
Ya está [terminado.](https://drive.google.com/file/d/0B836udDJlFJjSXFTRUJEM21JVUxSbHFLUzJVY1lEX3luenhZ/view?usp=sharing)

**Comment by profeIAP** [comment]
Pues me gustaría estar de acuerdo Elena pero hay momentos de silencio repentinos que evitan oír tus explicaciones 😳

Agradecería le echases un vistazo

**Comment by elenashp** [comment]
Lo he [corregido](https://drive.google.com/file/d/0B836udDJlFJjR2tXUW9qemhnVVE/view?usp=sharing).

**Comment by profeIAP** [comment]
Me gusta la música (aunque debería estar algo más baja para que se te escuche mejor a ti ya que tus explicaciones son las realmente importantes).

No obstante, la tarea la abro porque la resolución del vídeo ha bajado a 480p cuando todos los trabajos están, como mínimo a 720p

**Comment by elenashp** [comment]
Ya lo he [cambiado](https://drive.google.com/file/d/0B836udDJlFJjakxQNDBoLW93TFU/view?usp=sharing).

**Comment by profeIAP** [comment]
Aunque el vídeo indica que está a 720p, observa que hay un amplio margen negro rodeando la imagen principal.

**Comment by elenashp** [comment]
Aquí lo [tienes](https://drive.google.com/file/d/0B836udDJlFJjQVFFTHdWMnYzeUE/view?usp=sharing)

**Comment by profeIAP** [comment]
Se corta antes de terminar ¿qué ha pasado?

**Comment by elenashp** [comment]
Problema al rendizarlo

**Comment by profeIAP** [comment]
Bueno, tendremos que verlo en clase... no te preocupes

**Comment by profeIAP** [comment]
Tras verlo en clase, observo que se corta abruptamente pero está completo, gracias Elena
