### ISSUE TITLE
Editar vídeo cómo instalar un plugin en Gimp

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#109]
Usando PiTiVi, editar el vídeo de la tarea #83 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by profeIAP** [comment]
Te asigno la tarea al considerar más lógico que seas tú quien resuelva el embrollo de vídeos y audios que has creado... ¿quién conoce mejor el trabajo que tú? 😏

**Comment by sofialg** [comment]
aquí tienes la [edición](https://drive.google.com/open?id=0ByX9-8bPmeb4amhUWG5KTU43NVk)

**Comment by profeIAP** [comment]
Gracias Sofía, pero recuerda subir el resultado de renderizar el trabajo en lugar del fichero del proyecto que has creado con PiTiVi 😅

**Comment by sofialg** [comment]
Aquí tienes la [edición](https://drive.google.com/open?id=0ByX9-8bPmeb4WlFoYnB1ZmJ2Wm8) corregida.

**Comment by profeIAP** [comment]
Aunque acelerado todo el proceso (creo que tengo taquicardia y todo ahora mismo 😂) ha quedado muy bien... gracias Sofia, buen trabajo a pesar de los obstáculos para la dicción 😉
