### ISSUE TITLE
Grabar cómo recortar una secuencia de vídeo en PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#11]
Crear un vídeo en el que se muestre cómo eliminar fragmentos de vídeo que no interesen utilizando PiTiVi

**Comment by albavera** [comment]
El enlace del [video](https://drive.google.com/drive/folders/0B1or4uFFvPJ-SVljVTNyQ25RRWM)

**Comment by albavera** [comment]
El enlace del [video](https://drive.google.com/file/d/0BwM4Yi3Ht1DzUXNablY0TUlNVjA/view?usp=sharing)

**Comment by profeIAP** [comment]
Perfecto Alba, buen trabajo.
