### ISSUE TITLE
Editar vídeo cómo obtener la dirección MAC en Windows

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#112]
Usando PiTiVi, editar el vídeo de la tarea #77 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by daniveg20** [comment]
Hola maestro, aquí te dejo la edición de [como obtener la direción  MAC de nuestro ordenador Window](https://drive.google.com/open?id=0B7Bi54VPufr-UmlNb1FTSUMzR3c)

**Comment by profeIAP** [comment]
Hay algo raro en ese vídeo Daniel ¿has usado el vídeo que tiene el /all pegado a ipconfig?

**Comment by daniveg20** [comment]
Hola maestro, aquí te dejo la edición de [como obtener la direción MAC de nuestro ordenador Window](https://drive.google.com/open?id=0B7Bi54VPufr-UmlNb1FTSUMzR3c)

**Comment by profeIAP** [comment]
Los nervios te juegan malas pasadas (como pulsar el botón ¿enter? o la ¿tecla Aceptar?) pero se comprende 😂

Me gusta la imagen introduciendo el vídeo que pones al principio pero no tanto que se corte abruptamente el vídeo con tus explicaciones cuando da la sensación de que vas a decir algo más.

En fin, un trabajo muy aceptable pero que quedaría en un 9 en lugar de un 10 por esos nímios detalles... ¡seguro que la próxima lo haces mucho mejor! ;)
