### ISSUE TITLE
Editar vídeo cómo mostrar un selector de fechas en Google Sheets

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#116]
Usando PiTiVi, editar el vídeo de la tarea #69 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by albaag20** [comment]
esta [aqui](https://drive.google.com/open?id=0B7VbTuFV9GGEUEpsc1BPUkVhbms)

**Comment by profeIAP** [comment]
Gracias Alba, pero has subido el proyecto de PiTiVi en lugar del fragmento de vídeo renderizado 😅

**Comment by albaag20** [comment]
Aqui lo [tienes](https://drive.google.com/open?id=0B7VbTuFV9GGEajl2bkQ1VTZjMDg)

**Comment by profeIAP** [comment]
Perfecto Alba, buen trabajo.
Gracias
