### ISSUE TITLE
Editar vídeo cómo iniciar la "navegación privada" en el navegador

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#120]
Usando PiTiVi, editar el vídeo de la tarea #61 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by Ezki14** [comment]
Tarea [hecha](https://drive.google.com/file/d/0B0QdTXKv7lZ5LUdNUUU3NGg2WWM/view?usp=sharing)

**Comment by profeIAP** [comment]
Se me han "saltado las lágrimas" y todo 😜

El primer vídeo completo elaborado por @Ezki14, @Frangamboag e @irene32 

¡Muy buen trabajo! y mi enhorabuen a todos cada uno de vosotros, os ha quedado genial, gracias.
