### ISSUE TITLE
Editar vídeo cómo eliminar claves almacenadas en el navegador

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#121]
Usando PiTiVi, editar el vídeo de la tarea #59 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by aliciavalle15** [comment]
Aquí tienes el [video editado ](**https://drive.google.com/open?id=0BytR8hopIxdmekRLSzJqOW41MVE**)

**Comment by aliciavalle15** [comment]
Aquí tienes el [video editado.](https://drive.google.com/open?id=0BytR8hopIxdmekRLSzJqOW41MVE)

**Comment by profeIAP** [comment]
Parece que ha quedado muy bien pero la calidad del vídeo es nefasta.
Los ficheros originales son de 720p y así debería quedar el trabajo final, Alicia.
Por suerte apenas cuesta trabajo arreglarlo por lo que te agradecería que lo dejes como estamos acostumbrados ;)

**Comment by aliciavalle15** [comment]
Aquí esta de nuevo el [video editado](https://drive.google.com/open?id=0BytR8hopIxdmRFhVbF8wVUFuVms).

**Comment by profeIAP** [comment]
Simplemente espectacular, muchísimas gracias Alicia, te ha quedado muy bien y ¡hasta con música de fondo!

Lo dicho: ¡espectacular!
