### ISSUE TITLE
Editar vídeo cómo cerrar la sesión en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#122]
Usando PiTiVi, editar el vídeo de la tarea #57 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by profeIAP** [comment]
Quito la asignación a Sofia tras decidir que es la más indicada (y cualificada) para realizar la tarea de edición #109)

**Comment by maricarmen01** [comment]
Aquí está el [vídeo editado](https://drive.google.com/open?id=0BzuXr9g-7qn3VFRIc0lFZFhfc3c)

**Comment by profeIAP** [comment]
Perfecto, gracias Mª Carmen.
Muy buen trabajo
