### ISSUE TITLE
Editar vídeo cómo hacer una captura de pantalla en nuestro ordenador

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#124]
Usando PiTiVi, editar el vídeo de la tarea #54 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by albertvm10** [comment]
Aqui lo [tienes](https://drive.google.com/open?id=0B2w8fNHSCgBqVm5oT0ZxZm1sVG8
)

**Comment by albertvm10** [comment]
Maestro este es el nuevo[ video](https://drive.google.com/open?id=0B2w8fNHSCgBqdllkZmtIdG9uOGs), el otro era un error

**Comment by profeIAP** [comment]
Fantástico, gracias Alberto, ha quedado muy bien.
