### ISSUE TITLE
Editar vídeo cómo eliminar el audio de un vídeo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#125]
Usando PiTiVi, editar el vídeo de la tarea #52 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by SantiagoJiBe** [comment]
[hecho](https://drive.google.com/open?id=0BxHuCXCBd50vVEFsSXp4NFF1Y0U) maestro, a ver que te parece

**Comment by profeIAP** [comment]
No tiene mala pinta Santi (gracias) pero la resolución es 480p en lugar de los 720p del vídeo original

**Comment by SantiagoJiBe** [comment]
maestro esta es la mejor calidad a la que lo puedo poner
[enlace](https://drive.google.com/open?id=0BxHuCXCBd50vZEtoOE9OTllMd1k)

**Comment by SantiagoJiBe** [comment]
Maestro lo he intantado
 hacer con otro pc pero no lo he podido poner a mejor calidad.
La mejor calidad posible ha sido [esta](https://drive.google.com/open?id=0BxHuCXCBd50vVEFsSXp4NFF1Y0U)

**Comment by profeIAP** [comment]
Ya lo hemos hablado en clase...

**Comment by SantiagoJiBe** [comment]
Maestro, creo que lo [consegui](https://drive.google.com/open?id=0BxHuCXCBd50vbXJKam1WSEhVME0
)

**Comment by SantiagoJiBe** [comment]
Tengo un problema
Si recuerdas, esta mañana te comente quelo intentaria hacer en casa pero este ordenador tiene windows 10 y el reproductor no es capaz de reproducir el video, por lo consiguiente, no puedo editar el video como desearía

**Comment by SantiagoJiBe** [comment]
Vale maestro, resulta que he rebuscado en mi drive todos los intentos de edicion y..., de la nada a aparecido [este](https://drive.google.com/open?id=0BxHuCXCBd50vbXJKam1WSEhVME0)
asi que listo

**Comment by profeIAP** [comment]
LOL!! Te ha quedado hasta bien 😂
Gran trabajo Santi, gracias.
Lástima que no hayamos aprendido dónde estaba el "truco" 🤔
