### ISSUE TITLE
Editar vídeo cómo "soltar" una tarea que tenemos asignada en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#129]
Usando PiTiVi, editar el vídeo de la tarea #44 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by juankagb00** [comment]
[Edición](https://drive.google.com/open?id=0BzGsa6imqpYJWnY2T1hTNXVtbUE)

**Comment by profeIAP** [comment]
JuanKa el vídeo está a 480p cuando realmente debería ser a 720p como todos los vídeos que estamos generando.

Por suerte es tan sencillo como volver a renderizar cambiando la configuración (siempre y cuando tengas el proyecto de PiTiVi guardado)

**Comment by juankagb00** [comment]
Vale el proximo dia lo hago porque creo que lo guardé.

**Comment by juankagb00** [comment]
[Edición](https://drive.google.com/open?id=0BzGsa6imqpYJZnFNekdMWml3SkU)

**Comment by profeIAP** [comment]
Tiene muy buena pinta pero renderiza a 720p para que se vea en el tamaño original de vídeo que estamos usando en las grabaciones, please

**Comment by profeIAP** [comment]
Sigue estando a 480p ¿?

**Comment by juankagb00** [comment]
[Edición](https://drive.google.com/file/d/0BzGsa6imqpYJOGtxNWozVVRaQkE/view?usp=sharing)

**Comment by profeIAP** [comment]
No está a 720p, observa que tiene bordes negros para "aburrirse" (y/o rellenar a 720p)

![captura de pantalla de 2017-03-30 12-43-00](https://cloud.githubusercontent.com/assets/16881846/24500643/7adcd354-1546-11e7-8b6b-5f6e81eaf9b7.png)

**Comment by juankagb00** [comment]
Pues entonces nose bueno me podrias decir una aplicacion para editar en
window para hacerlo por ahí ave si me deja.

**Comment by profeIAP** [comment]
Hay muchos pero no cuento con tiempo (ni experiencia pues soy 100% Linux, en casa también)
Prueba con Windows Movie Maker Juan Carlos y evita, en la medida de lo posible las faltas de ortografía pues, serán tenidas en cuenta para poder cerrar la tarea ;)

**Comment by profeIAP** [comment]
El [nuevo vídeo](https://drive.google.com/open?id=0B1or4uFFvPJ-dTQ1dFRaYURvOE0)

**Comment by profeIAP** [comment]
El tamaño ha mejorado pero me temo que a costa de perder calidad (escalado?) lo cual hace que se vea excesivamente borroso (resulta incómodo)

**Comment by juankagb00** [comment]
[Edición](https://drive.google.com/open?id=0BzGsa6imqpYJR0dic1o5NWZocTQ)

**Comment by profeIAP** [comment]
Lo veo en "cinemascope" pero he debido quedarme sordo (de un pie)

**Comment by juankagb00** [comment]
[Edición](https://drive.google.com/open?id=0BzGsa6imqpYJSnRacHpZWFZTaG8)

**Comment by profeIAP** [comment]
Perfecto, gracias
