### ISSUE TITLE
Grabar cómo registrar sonidos con Audacity

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#13]
Crear un vídeo en el que se muestre cómo se graba audio utilizando Audacity

**Comment by Frangamboag** [comment]
Tarea hecha, [https://youtu.be/3xGJEg0wwjM](url)

**Comment by profeIAP** [comment]
Creo que este es el único vídeo del que nos has "cedido voluntariamente" los derechos de autor 😂

Otra cosa es que sospecho que todavía no has aprendido a enlazar en github (#46) pues me ha tocado editar el comentario anterior ¿?
