### ISSUE TITLE
Editar vídeo cómo asignarnos una tarea en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#130]
Usando PiTiVi, editar el vídeo de la tarea #42 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by mariateresapg01** [comment]
Listo! Te dejo el [enlace](https://drive.google.com/file/d/0B77IAfhm-w9pYi0xRHRjREkwTVk/view?usp=sharing)

**Comment by profeIAP** [comment]
Demasiado pequeño, Teresa.
No se ve nada

**Comment by mariateresapg01** [comment]
[Te lo dejo](https://drive.google.com/file/d/0B77IAfhm-w9pb0JjQjM1S05La0E/view?usp=sharing) de nuevo

**Comment by profeIAP** [comment]
Ahora si que se ve perfecto... muchas gracias Teresa.
Igual a @SantiagoJiBe le viene bien que compartas con él cómo lo has hecho ;)
