### ISSUE TITLE
Editar vídeo cómo eliminar ruido de una pista de audio

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#132]
Usando PiTiVi, editar el vídeo de la tarea #20 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by humanes14** [comment]
[Hecho](https://drive.google.com/file/d/0B0jFhmGL6h-AeEdSd2VmdlUteW8/view?usp=sharing)

**Comment by profeIAP** [comment]
Te ha quedado francamente bien pero, como te comenté en la tarea de narración #39, los tiempos no terminan de cuadrar; especialmente se nota en las dos veces que se accede al filtro de reducción de ruído.

Necesitaría lo cuadrases para poder dar por finalizada esta tarea

**Comment by humanes14** [comment]
Maestro creo que ya esta arreglado, volvi a hacer la narracion de nuevo, [aqui lo tienes](https://drive.google.com/file/d/0B0jFhmGL6h-AWmRnWUFUcDBoUm8/view?usp=sharing)

**Comment by profeIAP** [comment]
Fantástico... aunque va un poco por delante el sonido que el vídeo y los valores que se indican no coinciden con lo que se ven en la pantalla pero el resultado es "potable"

Gracias
