### ISSUE TITLE
Editar vídeo cómo renderizar vídeos con PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#133]
Usando PiTiVi, editar el vídeo de la tarea #19 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by daniveg20** [comment]
Hola maestro, te envío también el [trabajo](https://drive.google.com/open?id=1Xs1MuZndfR3S_wE_vA_Dd7DiTzJlz1oh) por ahí además de por Classroom para asegurarme de que no me falte nada

**Comment by profeIAP** [comment]
Perfecto Dani, buen trabajo 👍
