### ISSUE TITLE
Editar vídeo cómo añadir una pista de audio en PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#135]
Usando PiTiVi, editar el vídeo de la tarea #17 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by Carjop** [comment]
[Edición](https://drive.google.com/open?id=0B8tTRlqZUkjnVmdzTWFBM244V3M)

**Comment by profeIAP** [comment]
Puaj... se está extendiendo la plaga del 480p pero ahora "escalado" a 1080p 😳

**Comment by Carjop** [comment]
[Edición](https://drive.google.com/open?id=0B8tTRlqZUkjnOEhnNjVQMy1XM1E)

**Comment by profeIAP** [comment]
Esta tarea no tiene sentido pues has editado la narración y la edición sin haber sido validadas previamente. Descarto el trabajo entregado (sorry)

**Comment by Carjop** [comment]
[Edición](https://drive.google.com/open?id=0B8tTRlqZUkjnalBZTkZyWXg5QzA)

**Comment by profeIAP** [comment]
Estupendo.
Gracias Carlos, buen trabajo
