### ISSUE TITLE
Editar vídeo cómo unir dos pistas de audio en Audacity

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#138]
Usando PiTiVi, editar el vídeo de la tarea #14 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by ivanhumanes20** [comment]
[Tarea](https://drive.google.com/file/d/0B3QPZY-XeQ_eVl85d3hLQnE5MlU/view?usp=sharing) terminada

**Comment by profeIAP** [comment]
Te ha quedado muy bien Iván... lástima que no hayas dejado que se escuche un poco del resultado (ya que no se hace en el resto de la grabación para que se te oiga a ti) cuando @Frangamboag utiliza el reproductor ;)
