### ISSUE TITLE
Editar vídeo cómo registrar sonidos con Audacity

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#139]
Usando PiTiVi, editar el vídeo de la tarea #13 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by FraniBL** [comment]
[Hecho](https://drive.google.com/file/d/0B5qdPOBTbGERTEhWY3AxUWhILVk/view?usp=sharing) He necesitado algun que otro corte y aumentar un poco la velocidad del video para que cuadrara con el audio, pero poco más

**Comment by profeIAP** [comment]
Sí que va "aceleradillo" pero ha quedado muy bien, gracias y enhorabuena Frani
