### ISSUE TITLE
Editar vídeo cómo recortar una secuencia de vídeo en PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#141]
Usando PiTiVi, editar el vídeo de la tarea #11 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by albavera** [comment]
El enlace del [video](https://drive.google.com/file/d/0BwM4Yi3Ht1DzaXBjRVplS0ZybE0/view?usp=sharing) editado

**Comment by profeIAP** [comment]
Genial, buen trabajo Alba
