### ISSUE TITLE
Editar el cambio de NAT a "Adaptador puente" en una máquina virtual

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#143]
Usando PiTiVi, editar el vídeo de la tarea #9 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by marielasan11** [comment]
Aquí dejo el [vídeo editado](https://drive.google.com/open?id=0BwBwdkQMENfYLVBHTFpNMXlzaFk) en el que se explica el cambio de NAT a Adaptador puente en una máquina virtual.

**Comment by profeIAP** [comment]
Simplemente espectacular Mariela, gracias.

La única pega que le encuentro es que el vídeo ha pasado a 480p (en lugar de los 720p que tenía tu grabación original) y desmerece el resultado final.

Es una tontería en la configuración de PiTiVi al exportar, si no lo encuentras, dímelo y te ayudo.

**Comment by marielasan11** [comment]
Se le puede cambiar la calidad a un vídeo ya exportado?🤔
No me digas que voy a tener que hacerlo de nuevo?😰

**Comment by marielasan11** [comment]
[Video nuevo y corregido](https://drive.google.com/open?id=0BwBwdkQMENfYWEptOVRDUXZkbjQ) en el que se ve el cambio de NAT a adaptador puente

**Comment by profeIAP** [comment]
Te ha quedado genial Mariela, ¡enhorabuena!

**Comment by marielasan11** [comment]
Muchas gracias😊

**Comment by profeIAP** [comment]
A ti por un trabajo bien hecho
