### ISSUE TITLE
Grabar cómo comprimir varios archivos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#153]
Crear un vídeo en el que se muestre cómo crear un archivo comprimido a partir de varios archivos de un directorio.

Sería ideal que se eligiesen sólo algunos de los archivos de un directorio (quedando otros sin seleccionar) a la hora de crear el archivo comprimido

**Comment by Anyela3000** [comment]
Aqui tienes[ el video ](https://drive.google.com/file/d/0BzU1s9gbzwV7QmJLR1Nkd0s5bGs/view)

**Comment by profeIAP** [comment]
Está bastante bien Ángela pero agradecería:

1. Comprimieses una colección de archivos y carpetas (comprimes un par de carpetas y puede que tus compañeros no terminen de entender bien cómo se hace)
1. Sería interesante usar un formato más común en Windows (como zip, rar, arj o 7z)
1. Es un **requisito** ocultar todos los enlaces en los comentarios

Por lo demás está muy bien y me ha gustado mucho, gracias

**Comment by Anyela3000** [comment]
A ver si esta vez esta mejor, como comprimir varios archivos[](https://drive.google.com/file/d/0BzU1s9gbzwV7cUVoZTBENUdMZjA/viewl)

**Comment by profeIAP** [comment]
Seguro que está bien pero agradeceré el enlace al fichero subido 😉

**Comment by Anyela3000** [comment]
Aqui esta con el enlace del fichero subido, como comprimir varios archivos [https://drive.google.com/file/d/0BzU1s9gbzwV7cUVoZTBENUdMZjA/view](url)

**Comment by profeIAP** [comment]
Gracias Ángela pero el enlace:

1. no está oculto en el texto
1. no apunta al fichero que has subido

Por favor, corrígelo para que pueda evaluarlo, gracias.

**Comment by Anyela3000** [comment]
Espero que este esta vez correcto, [como comprimir varios archivos](https://drive.google.com/open?id=0BzU1s9gbzwV7cUVoZTBENUdMZjA)

**Comment by profeIAP** [comment]
Fantástico Ángela, buen trabajo.

La única pega es que sigo viendo enlaces sin ocultar en los comentarios y es preciso quitarlos para poder dar por cerrada la tarea.
