### ISSUE TITLE
Grabar cómo descomprimir un fichero comprimido

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#154]
Crear un vídeo en el que se muestre cómo descomprimir el contenido de un fichero comprimido cualquiera.

**Comment by Ezki14** [comment]
[Hecho](https://drive.google.com/file/d/0B0QdTXKv7lZ5czdZa0libURCdU0/view?usp=sharing)

**Comment by profeIAP** [comment]
El vídeo está bien pero el fondo no es _apropiado_.
Considero que debes volver a grabarlo "correctamente".
Gracias

**Comment by Ezki14** [comment]
[Cambiado](https://drive.google.com/file/d/0B0QdTXKv7lZ5RGxTMFFuV0NPeUk/view?usp=sharing)

**Comment by profeIAP** [comment]
Ezquiiiiiiiii.... si el fondo no es apropiado ¿¡¿por qué pierdes el tiempo descomprimiendo la foto de la "discordia"?!?

Queda anulado/betado por el mismo motivo 😞

**Comment by Ezki14** [comment]
[Ya esta](https://drive.google.com/file/d/0B0QdTXKv7lZ5dHM1aUthSDBMX2c/view?usp=sharing)

**Comment by profeIAP** [comment]
Podria servir (aunque, al curioso que llevo dentro, le hubiese gustado poder ver el contenido de dicha carpeta)

Gracias Ezequiel
