### ISSUE TITLE
Grabar cómo selecciona varios ficheros en un directorio

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#157]
Crear un vídeo en el que se muestre cómo utilizar las teclas CTRL(ficheros sueltos) y MAYÚSC. (ficheros próximos físicamente) para seleccionar varios ficheros de un directorio.

**Comment by JoseManueh** [comment]
Maestro. Creo que esta bien. Mira [Enlace a video](https://drive.google.com/drive/folders/0B1or4uFFvPJ-SVljVTNyQ25RRWM)

**Comment by profeIAP** [comment]
Me gustaría, pero ha enlazado la carpeta (en lugar del fichero) y el que lo necesite va a tener que "bucear" entre tanto "fichero suelto" 😜

**Comment by JoseManueh** [comment]
y que le parece a usted, su excelentísima, [esto?](https://drive.google.com/file/d/0B-3r8g9hTyCqQ1htV1RaT3FrVVE/view)

**Comment by profeIAP** [comment]
Pues su "excelencia" estima que:

1. al igual que las últimas grabaciones de @Frangamboag está "hipervitamidado" y 
1. no se observa el uso de la selección de un rango de ficheros mediante la tecla MAYUS

Me has recordado al príncipa de las letras españolas con su interpelación

![](https://i0.wp.com/alenarterevista.net/wp-content/uploads/2015/01/Cervates_jauregui.jpg)

Lo "ilustro" con la foto adjunta ;)

**Comment by JoseManueh** [comment]
bueno, es que de todas maneras, se veria mal, pero lo hare de nuevo

**Comment by JoseManueh** [comment]
lo he arreglado
aqui [justamenete, jate](https://drive.google.com/drive/folders/0B1or4uFFvPJ-SVljVTNyQ25RRWM)

**Comment by JoseManueh** [comment]
ahora si, que me equivoqué [han solo se muere en tfa](https://drive.google.com/drive/folders/0B1or4uFFvPJ-SVljVTNyQ25RRWM)

**Comment by profeIAP** [comment]
Pues te has debico de equivocar en ambos casos: recuerda enlazar el fichero concreto a mostrar en lugar de la carpeta (que está llena de trabajos ;P )

**Comment by JoseManueh** [comment]
[Y AHORA??? (NO CREO K ESTE MAL)(SOCORRO) ](https://drive.google.com/file/d/0B-3r8g9hTyCqQ1htV1RaT3FrVVE/view?usp=sharing)

**Comment by profeIAP** [comment]
No pidas "auxilio" que nadie te va a "salvar" 😏

Te ha quedado estupendamente bien, muchas gracias Jose Manuel
