### ISSUE TITLE
Grabar cómo mostrar el navegador a pantalla completa

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#159]
Crear un vídeo en el que se muestre cómo visualizar el contenido del navegador de modo que aproveche al máximo el espacio en pantalla.

**Comment by profeIAP** [comment]
Le asigno la tarea a @juannma1245 por ser quien me dió la idea para crear la tarea.

**Comment by juannma1245** [comment]
[Este es el enlace de la grabacion](https://drive.google.com/open?id=0B4rXBJ9q940bN1dfR2dxSnphbjQ)

**Comment by profeIAP** [comment]
Pegas muchos saltos y no termina de verse bien cómo se hace ¿no te parece?

**Comment by profeIAP** [comment]
Viéndolo de segundas no está tan mal... vamos para adelante Juanma

**Comment by juannma1245** [comment]
Vamos a intentar sacar otro 10 de media

**Comment by profeIAP** [comment]
Esa es la actitud... ¡Di que sí!

![8375iee3a2fd2c416ef20](https://cloud.githubusercontent.com/assets/16881846/22383961/840c146c-e4cc-11e6-8029-29d485fdb0d2.jpg)
