### ISSUE TITLE
Buscar una "cortinilla" de presentación

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#16]
Localizar (y elegir) un vídeo que sirva de [cortinilla de apertura](https://es.wikipedia.org/wiki/Cortinilla) a los vídeos que grabaremos en clase.

**NOTA 1:** La cortinilla debe tener licencia [Creative Commons](http://es.creativecommons.org/blog/licencias/) pudiendo ser usada libremente en nuestras producciones.

**NOTA 2:** Como me consta que tenemos algunos alumnos con "experiencia" en edición de vídeo, abro la puerta a negociar la dificultad de esta tarea (y premiar con puntos extra la "creatividad" y el trabajo original) ;)

**NOTA 3:** Etiqueto la tarea como _reto_ al tener que invertir bastante tiempo en la localización de una cortinilla que se ajuste a los requisitos establecidos y, al tratarse de algo tan subjetivo (por depender de los gustos personales de cada uno), arriesgarse a que la tarea no sea aceptada a la primera hasta que la elegida se ajuste a la temática de nuestras creaciones

**Comment by Frangamboag** [comment]
Tarea [hecha](https://youtu.be/vUEzYraQqe0)

NOTA 1: El audio está realizado uniendo dos canciones (la primera tiene licencia)

NOTA 2: La segunda canción no necesita licencia Creative Commons debido a que no supera los 10 segundos (a partir del cual sería infringir derechos de Copyright)
