### ISSUE TITLE
Grabar cómo eliminar un marcador del administrador de archivos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#161]
Crear un vídeo en el que se muestre cómo eliminar alguno de los marcadores que tengamos creados en nuestro administrador de archivos.

**Comment by Alba4** [comment]
Buenas tardes, aqui te dejo el video de como eliminar un marcador del administrador de archivos.
Te dejo aqui el [enlace](https://drive.google.com/open?id=0B5K_l_5BtyFVbXBteUl4RTJZTjQ) del video.
Salu2.

**Comment by profeIAP** [comment]
Genial Alba pero llama la atención que no aparezca en el margen izquierdo (junto al resto de opciones) el marcador que has eliminado

![captura de pantalla de 2017-02-01 16-47-45](https://cloud.githubusercontent.com/assets/16881846/22514028/485a4918-e89e-11e6-9fd2-8fb390fd58bb.jpg)

Lo he mirado varias veces pero debo estar con problemas de visión graves ¿?

Técnicamente y, partiendo de la difinición de la tarea, estaría bien lo que has hecho pero ¿te costaría mucho volver a grabarlo de modo que se vea en el margen? (resultaría más claro para tus compañeros y lo agradecerán)

**Comment by Alba4** [comment]
Arreglado el problema, te dejo aqui el [enlace](https://drive.google.com/open?id=0B5K_l_5BtyFVUnJKMVp2N0xPQUU) del nuevo el video ya arreglado.

**Comment by profeIAP** [comment]
Excesivamente rápido... no se ve lo que se está haciendo 😳

**Comment by Alba4** [comment]
Sin problema, el proximo dia lo arreglo.

**Comment by Alba4** [comment]
Aqui está de nuevo el [enlace](https://drive.google.com/open?id=0B5K_l_5BtyFVaXRTRnRFdUFMams) con el video, esta grabado lo más despacio posible, espero que este sea el bueno.
Saludos

**Comment by profeIAP** [comment]
Pefecto Alba, ha quedado perfecto.
¡Enhorabuena! (y gracias)
