### ISSUE TITLE
Grabar cómo crear un marcador en Mozilla Firefox

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#162]
Crear un vídeo en el que se muestre cómo anotar alguna página web (p.e. la web de nuestro proyecto de GitHub) en Mozilla Firefox

**Comment by JoseManueh** [comment]
Venga ivan. Lijero que tengo que editarlo

**Comment by profeIAP** [comment]
Siempre desde el "cariño" @ivanhumanes20 que @JoseManueh algunas veces se pone "nervioso" 😂

**Comment by ivanhumanes20** [comment]
Esta es la[ tarea](https://drive.google.com/file/d/0B3QPZY-XeQ_eRjg1RjlGdzVnelE/view?usp=sharing)

**Comment by profeIAP** [comment]
Aunque:

1. queda "feo" eso de "marcadores sin ordenar"
1. al no haber abierto una nueva pestaña y/o cambiado de página apenas se aprecia que se abre correctamente al elegir el marcador.

Podría servir... esperemos que el encargado de narrar el vídeo (¿verdad @JoseManueh ?) le de algo de "gracia" y se puedan apreciar los finos detalles de tu trabajo ;)

Si Alfredo considera que sería interesante incluir los detalles que indico le doy total libertad para expresarse y "exigir" (abriendo la tarea) que se tengan en cuenta ;)

**Comment by JoseManueh** [comment]
ivan. por tus nietos. surge de tus cenizas y graba el video plis

**Comment by profeIAP** [comment]
XD

**Comment by JoseManueh** [comment]
No estoy de broma. Mataré a 5 beivis si no lo haces...

**Comment by JoseManueh** [comment]
👍

**Comment by profeIAP** [comment]
No entiendo que "Alfredo" opte por abrir la tarea e Iván la cierre sin incluir los cambios "exigidos"... ¿lo aclaráis entre vosotros o hacemos una "quedada" en mi mesa para hablarlo?

**Comment by profeIAP** [comment]
Perfecto Iván, gracias.

No me había dado cuenta que habías actualizado [el enlace en tu último comentario](https://github.com/profeIAP/Documentacion/issues/162#issuecomment-278893137)
