### ISSUE TITLE
Grabar cómo crear un marcador en Googel Chrome

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#163]
Crear un vídeo en el que se muestre cómo anotar alguna página web (p.e. la web de nuestro proyecto de GitHub) en Google Chrome

**Comment by Jesusbg19** [comment]
[hecho](https://drive.google.com/file/d/0Bym9m5PPnKP-R0ZxM3VQYUZ5QzA/view?usp=sharing)

**Comment by profeIAP** [comment]
Está de lujo Jesús pero, personalmente, optaría por elegir el marcador de la lista
![captura de pantalla de 2017-01-27 19-48-17](https://cloud.githubusercontent.com/assets/16881846/22383343/b1dda03e-e4c9-11e6-8864-36ced39bc0f7.jpg)
en lugar de hacer que la gente muestre la molesta (las pantallas de los portátiles no son precisamente grandes y ocupa demasiado espacio) barra de marcadores.

¿Te costaría grabar el trocito que falta? (y lo solapamos con lo que ya tienes grabado por evitarte grabarlo entero)

**Comment by Jesusbg19** [comment]
[de nuevo, este puede valer?](https://drive.google.com/file/d/0Bym9m5PPnKP-SGk1ZFh1dm52Yzg/view?usp=sharing)

**Comment by profeIAP** [comment]
Sí pero el problema es que, en esa ocasión, has puesto en los marcadores la página de inicio del navegador en lugar de cualquier otra página (cita previa, proyecto de github, ...)

**Comment by Jesusbg19** [comment]
[Acabado, Este puede valer?](https://drive.google.com/file/d/0Bym9m5PPnKP-WENXMlctMlpyYlU/view?usp=sharing)

**Comment by profeIAP** [comment]
Jaaaaarrr... ¿¡¿por qué vuelves a mirar en PESTAÑAS RECIENTES en lugar de en MARCADORES?!?
¿Grabamos sólo ese trozo y lo "solapamos" con lo que ya tienes?

**Comment by Jesusbg19** [comment]
El trozo que [falta ](https://drive.google.com/file/d/0Bym9m5PPnKP-TVVsTEJiYmhaTW8/view?usp=sharing)

**Comment by profeIAP** [comment]
Gracias Jesús, pero has subido el proyecto de PiTiVi en lugar del fragmento de vídeo 😅

**Comment by profeIAP** [comment]
¿No hubiese quedado mejor que el ratón se hubiese "posado" en la parte inferior en la que se ve observa el marcador que has creado en lugar de en la primera opción del menú?

Personalmente me "confunde" pues haces demasiado hincapié en la zona del menú que no es...

![captura de pantalla de 2017-02-21 16-47-01](https://cloud.githubusercontent.com/assets/16881846/23172266/887b92ec-f855-11e6-9d5a-f25ec33bca9f.png)

**Comment by Jesusbg19** [comment]
Con [esta](https://drive.google.com/file/d/0Bym9m5PPnKP-SGk1ZFh1dm52Yzg/view?usp=sharing) ya no tiene que haber ningún problema

**Comment by profeIAP** [comment]
Efectivamente, está realmente bien.

Muchísimas gracias Jesús, ¡excelente trabajo!
