### ISSUE TITLE
Grabar cómo eliminar un marcador en Google Chrome

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#165]
Crear un vídeo en el que se muestre cómo eliminar alguno de los marcadores que hayamos creado en el navegador Google Chrome

**Comment by Josefco16** [comment]
Aqui tienes [el video](https://drive.google.com/open?id=0B6u8ft6cvaSUOGVRdWxwcFRuV2c) maestro

**Comment by profeIAP** [comment]
Está perfecto pero... si la tarea es para **Google Chrome** ¿¡¿por qué aparece Firefox en el vídeo?!? 😳

**Comment by Josefco16** [comment]
Ya lo e arreglado, aqui tienes el nuevo [video](https://drive.google.com/open?id=0B6u8ft6cvaSUNUVuR2p2T1dZR1E)

**Comment by profeIAP** [comment]
Genial, muchas gracias Francisco.
