### ISSUE TITLE
Grabar cómo adjuntar un fichero a GMail

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#166]
Crear un vídeo en el que se muestre cómo se añade un adjunto a un correo electrónico usando GMail

**Comment by portiii11** [comment]
Tarea terminada. Aqui te dejo el enlace. https://drive.google.com/file/d/0B65Jab81ULnMYXNSVVBDRlVKcmc/view?usp=sharing

**Comment by profeIAP** [comment]
Perfecto Porti, necesito que ocultes el enlace para dar por finalizada la tarea.
Gracias

**Comment by profeIAP** [comment]
Genial, gracias Antonio
