### ISSUE TITLE
Narrar cómo eliminar un marcador en Google Chrome

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#168]
Describir el proceso seguido en el vídeo de la tarea #165

**Comment by Josefco16** [comment]
Aqui tienes [la narración ](https://drive.google.com/open?id=0B6u8ft6cvaSUVGE4V2JZVTdBOE0)

**Comment by profeIAP** [comment]
No deberías haber acometido esta tarea sin estar "validada" la grabación por mi.
De momento no evalúo este trabajo pues no tiene sentido mientras que la grabación no sea aceptada.

**Comment by Josefco16** [comment]
Aqui tienes el[ audio](https://drive.google.com/open?id=0B6u8ft6cvaSUbVhkaXBkX2tObm8) arreglado

**Comment by profeIAP** [comment]
Te ha quedado muy bien salvo que el botón es el **derecho** (en lugar del izquierdo)
Sospecho que los nervios te han jugado una mala pasada ;)

**Comment by Josefco16** [comment]
Ya esta arreglado aqui tienes el [audio](https://drive.google.com/open?id=0B6u8ft6cvaSUYmotNEdoS2pWeWc)

**Comment by profeIAP** [comment]
Perfecto José Fco. comentar a @prainplayx que, cuando edite el vídeo (tarea #182) elimine lo que "sobra" al final (que coincide cuando tú te callas y no narras nada más)
Gracias
