### ISSUE TITLE
Grabar cómo añadir una pista de audio en PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#17]
Crear un vídeo en el que se muestre cómo añadir una pista de audio (p.e. una melodía de fondo) a un vídeo

**Comment by Frangamboag** [comment]
.

**Comment by profeIAP** [comment]
Recuerda subir el vídeo a la carpeta que hemos compartido en Drive y enlazarlo desde aquí para dar por finalizada la tarea y poder cerrarla.

**Comment by Carjop** [comment]
[Vídeo](https://drive.google.com/open?id=0B8tTRlqZUkjnUzBoVlR1b09BWkU)

**Comment by profeIAP** [comment]
Pardiez eZto qué es... ¿¡¿un vídeo a 480p?!? eso no se puede ni ver.

Siento que haya sido grabado en un Guadalinex de la época de la polca pero, en la era del 4K, que menos que una grabación en HD (720p)

**Comment by Carjop** [comment]
Problema solucionado. Vídeo renderizado a 1080p.

**Comment by profeIAP** [comment]
Gracias Carlos, no olvides subirlo porque el último enlace que has puesto sigue enlazando al vídeo a 480p

**Comment by Carjop** [comment]
[Video](https://drive.google.com/open?id=0B8tTRlqZUkjnZjhCOGpMdkVfWFk)

**Comment by profeIAP** [comment]
Visto lo visto y, viendo el tiempo que tienes, te sugeriría coger cualquier tarea que no suponga usar herramientas exclusivas de Guadalinex (para que puedas grabarlo y narrarlo en el "ventanuco" de MicroShoft)

Aceptaría incluso cualquier propuesta de tarea que, sin estar recogida todavía, crearía "ex profeso". Te dejo libertad de elección y, si te hiciese falta, hay tareas con Gimp que serían de utilidad (único requisito que impondré a la decisión que tomes). Se me ocurre (a bote pronto) exportar cualquier edición con Gimp a JPG (o PNG) pues estoy observando que los alumnos de 2eso están teniendo problemas.

**Comment by Carjop** [comment]
[Vídeo](https://drive.google.com/open?id=0B8tTRlqZUkjnSXNHajZWdzAtWFk)

**Comment by profeIAP** [comment]
Perfecto, gracias Carlos
