### ISSUE TITLE
Narrar cómo crear un marcador en Googel Chrome

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#170]
Describir el proceso seguido en el vídeo de la tarea #163

**Comment by Jesusbg19** [comment]
[aqui nuevo](https://drive.google.com/file/d/0Bym9m5PPnKP-YXdDMTRyUmxuRUE/view?usp=sharing)

**Comment by profeIAP** [comment]
Gracias Jesús pero aprovecha el tiempo y no narres nada mientras que no sea aceptada la tarea de grabación.

**Comment by Jesusbg19** [comment]
Ya te he enviado el vídeo, aqui esta el [audio](https://drive.google.com/file/d/0Bym9m5PPnKP-TjA0SThUOVNvdE0/view?usp=sharing)

**Comment by profeIAP** [comment]
Se te escucha realmente bien y vas muy tranquilo narrando, enhorabuena Jesús.

La única pega es que no veo que se pueda sincronizar correctamente el vídeo que has grabado con esta narración ¿estabas describiendo lo que veías o has estado leyendo un papel ante el micrófono?

He mirado si tenías asignada [la tarea de edición](https://github.com/profeIAP/Documentacion/issues/184) pero observo que la tiene @prainplayx, así que dejo en sus manos decidir si cree poder hacer cuadrar ambos trabajos o, si por el contrario, considera que deberías volver a narrarlo de forma que se ajuste.

**Comment by prainplay** [comment]
estaba describiendo lo que veía

**Comment by profeIAP** [comment]
Aún así no cuadra, esperamos a ver qué dice Jesús que, al fin y al cabo, es al que va a tocar arreglar el "entuerto" ¿no te parece?

**Comment by Jesusbg19** [comment]
Jesús, vas a hacer esta tarea o me la dejas a mi que tengo la narración y la grabación y me es más cómodo?

**Comment by profeIAP** [comment]
Como acordamos, lo he hablado con @prainplayx.

Como se fué "pensando" agradecería confirmación mediante un comentario (así @Jesusbg19 podrá empezar lo antes posible y/o elegir otra tarea en función de la decisión)

**Comment by prainplay** [comment]
te la dejo a ti

**Comment by profeIAP** [comment]
Gracias Jesús... ¿has elegido ya otra tarea de edición?

**Comment by Jesusbg19** [comment]
[](https://drive.google.com/file/d/0Bym9m5PPnKP-YXdDMTRyUmxuRUE/view?usp=sharing)

**Comment by Jesusbg19** [comment]
[aqui](https://drive.google.com/file/d/0Bym9m5PPnKP-YXdDMTRyUmxuRUE/view?usp=sharing)

**Comment by profeIAP** [comment]
Te ha quedado muy bien, enhorabuena Jesús.

La única pega (siento tener casi siempre una 😅) es que los tiempos no coinciden y la tarea de edición (aunque te la has asignado recientemente) pertenece (nuevamente) a @prainplayx.

Técnicamente, sólo te ha cedido esta tarea, pero vuelve a tener el problema (al no coincidir los tiempos de lo que se dice y ve) de tener que decidir entre:

1. Aceptar el reto de hacerlo cuadrar (quedándose con la tarea de edición)
1. Solicitar que cuadren los tiempos del vídeo y la narración.
1. Cederte la tarea de edición para que seas tú quien obre el "milagro"

Esperamos tu decisión @prainplayx  para ver si se puede cerrar (o no) esta tarea 😏

**Comment by Jesusbg19** [comment]
[aquí está, ya coinciden los tiempos](https://drive.google.com/file/d/0Bym9m5PPnKP-MXoxeFNWZnhCOUE/view?usp=sharing)

**Comment by profeIAP** [comment]
Buen trabajo Jesús.
Muchas gracias
