### ISSUE TITLE
Narrar cómo crear un marcador en Mozilla Firefox

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#171]
Describir el proceso seguido en el vídeo de la tarea #162

**Comment by JoseManueh** [comment]
¿nos alijeramos señore? que tengo que editar el video

**Comment by JoseManueh** [comment]
Señor profesor, ¿está bien? [aquí](https://drive.google.com/open?id=0B-3r8g9hTyCqNldvYTZuc2V3Qk0)

**Comment by profeIAP** [comment]
Perfectísimo excelentísimo alumno :P
