### ISSUE TITLE
Editar vídeo cómo crear un marcador en Google Chrome

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#184]
Usando PiTiVi, editar el vídeo de la tarea #163 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by prainplayx** [comment]
https://drive.google.com/open?id=0B9lsiGwGvCMTeWREYTlRV2lUc28

**Comment by profeIAP** [comment]
Jesús tengo algunas dudas:

1. En el vídeo ni se oye ni se hace nada (salvo mostrar la "archiconocida" página de Marca)
1. Debes ocultar los enlaces en los comentarios que realices (el que tienes en tu comentario anterior, debe "desaparecer"... pero que parezca un "accidente" 😏)

**Comment by prainplayx** [comment]
[aqui el video](https://drive.google.com/open?id=0B3GMW7GMWk9MVzJsNDVZV21qOXM)

**Comment by profeIAP** [comment]
Jesús debía desaparecer el enlace ¡no el comentario completo! 😳

No obstante, parece que has enlazado un vídeo incorrecto (es un trabajo de @FcoHumanessab)

Corrige, por favor, que nos vamos a liar

**Comment by prainplayx** [comment]
Aqui el [video](https://drive.google.com/open?id=0B9lsiGwGvCMTTkpWN3VJdGdXMm8)

**Comment by profeIAP** [comment]
Mucho mejor pero:

1. parecen faltar fragmentos del vídeo (fotogramas)
1. como tarea de **edición** se debe coger el vídeo que se indica en la descripción de esta tarea (y ha sido grabado ya por @Jesusbg19) y el audio en el que se narra lo que se hace en él (que lo tienes cogido tú con el perfil anterior y deberías cambiarlo si quieres que se te contabilice correctamente el trabajo)

Observa que he sugerido algunos cambios a @Jesusbg19 por lo que
1. deberás esperar a que lo grabe correctamente (y yo lo acepte)
1. buscar otra tarea de edición

Si no he sabido explicarme correctamente y/o te quedan dudas, pregunta en los comentarios o directamente en clase cuando tengas ocasión.

Ánimo

**Comment by Jesusbg19** [comment]
Jesús, me dejas esta tarea para tener las 3 de lo mismo?

**Comment by profeIAP** [comment]
Acabamos de hablarlo @Jesusbg19, puedes coger la tarea sin problemas... ¡suerte!

**Comment by Jesusbg19** [comment]
vale, ya la he asignado. Gracias!!

**Comment by profeIAP** [comment]
Gracias a los dos por la colaboración y el compañerismo

**Comment by Jesusbg19** [comment]
[Aquí dejo la tarea de edición](https://drive.google.com/file/d/0Bym9m5PPnKP-bWxxWlZZVnBBbmc/view?usp=sharing)

**Comment by profeIAP** [comment]
Fantástico Jesús, gran trabajo 👍
