### ISSUE TITLE
Editar vídeo cómo crear un marcador en Mozilla Firefox

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#185]
Usando PiTiVi, editar el vídeo de la tarea #162 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by JoseManueh** [comment]
[Terminé (creo)](https://drive.google.com/open?id=0B-3r8g9hTyCqVkRpZGloNlFtOVU)

**Comment by profeIAP** [comment]
Pues me temo que, aún con mucha fe, no puedo creer lo mismo que ud.

El audio no se escucha (está distorsionado) y el vídeo es de 480p (en lugar de los 720p originales)

**Comment by JoseManueh** [comment]
[¿y ahora? Y dime si cuenta, por favor](https://drive.google.com/open?id=0B-3r8g9hTyCqX05ERlpmcHVHcXc)

**Comment by profeIAP** [comment]
Desgracidamente está fuera de plazo Jose Manuel... se contará pero para la nota final (la foto "finish" quedó fijada este viernes, "sorry")

**Comment by JoseManueh** [comment]
De todas maneras, la presentación me ha aprobado no?

**Comment by profeIAP** [comment]
Te ha quedado estupendo, gracias
