### ISSUE TITLE
Grabar cómo renderizar vídeos con PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#19]
Crear un vídeo en el que se muestre cómo exportar en vídeo los trabajos realizados con PiTiVi

**Comment by FraniBL** [comment]
Tarea hecha. [https://drive.google.com/file/d/0B5qdPOBTbGERMDFPRUpaTkhhcUE/view](url)

**Comment by profeIAP** [comment]
Perfecto Fran (salvo por no ocultar el enlace jejeje)

**Comment by FraniBL** [comment]
[Solucionado](https://drive.google.com/file/d/0B5qdPOBTbGERMDFPRUpaTkhhcUE/view?usp=sharing)

**Comment by profeIAP** [comment]
¿Y el enlace d[el comentario de 16/dic](https://github.com/profeIAP/Documentacion/issues/19#issuecomment-267663833)?

**Comment by profeIAP** [comment]
Perfecto, muy buen trabajo, gracias.
