### ISSUE TITLE
Grabar cómo crear un código QR

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#196]
Crear un vídeo en el que se muestre cómo generar un código QR a partir de cualquier dirección web.
![](http://cdnqrcgde.s3-eu-west-1.amazonaws.com/wp-content/uploads/2013/11/jpeg.jpg)
Para ello utilizaremos cualquiera de los múltiples servicios online que existen.

**Comment by gabrobtruj** [comment]
maestro para escoger una tarea era en suscribir no??

**Comment by profeIAP** [comment]
Lo tienes explicado en la tarea #42 

No obstante Gabriel:
1. Agradecería que no uséis los comentarios para preguntar cosas no relacionadas con la tarea a la que pertenecen los comentarios (evitemos los comentarios "off-topic" podéis preguntar en clase aunque sea al entrar o salir del aula)
1. Veo que ante la duda que has tenido, se te ha adelantado Andrés 😳

No te preocupes, quedan muchas [tareas libres e interesantes](https://github.com/profeIAP/Documentacion/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Av%C3%ADdeo) para ti

**Comment by gabrobtruj** [comment]
bueno la verdad es que se me acaban las faciles no? intentare hacer o que
pueda

**Comment by profeIAP** [comment]
No te preocupes, te saldrá bien.
Cualquier duda ya sabes: pide "cita" y te "asesoro" sobre la tarea que escojas 👍

**Comment by gabrobtruj** [comment]
gracias lo hare si lo necesito

**Comment by AndresMAPE** [comment]
Aquí tienes [el vídeo](https://drive.google.com/file/d/0BzOpMWZn18xJdHJkRk83RjVTT1k/view?usp=sharing)

**Comment by profeIAP** [comment]
Muy bien @AndresMAPE, ¡buen trabajo!

Sobra parte del final, y titubeas en algunos momentos pero es poca cosa y confío que @daniveg20 sabrá arreglarlo en la tarea de edición.

**Comment by AndresMAPE** [comment]
Gracias maestro mañana lo editaré y narraré la parte que me toca gracias
por confiar en mi ;)

**Comment by profeIAP** [comment]
A ti, Andrés
