### ISSUE TITLE
Grabar cómo añadir contactos a un grupo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#2]
Crear un vídeo en el que se muestre cómo se agrupan contactos que tenemos en nuestra agenda a un grupo ya existente.

**Comment by felixgp00** [comment]
Ya he terminado la tarea este es el enlace para ver [el video](https://drive.google.com/open?id=0B_WgVEzfcQzfTUVvMHRhUE9pcVk)

**Comment by profeIAP** [comment]
Félix, la calidad es nefasta (para muestra un botón)

![captura de pantalla de 2016-12-13 17-20-32](https://cloud.githubusercontent.com/assets/16881846/21148440/85e6209e-c158-11e6-8d99-a432b0636bd3.png)

¿Se ve bien en tu equipo? (no descarto que sea cosa mía pero tiene pinta de haber bajado demasiado la calidad al grabar)

Igualmente, procura ocultar los enlaces en el texto del comentario anterior (queda feo que se vea la url ¿no te parece?)

**Comment by felixgp00** [comment]
Es cosa del equipo, intente mejorar la calidad de grabación, pero no encontre opciones para ello.


No entiendo lo que me dices de los enlaces ¿como puedo quitar la url?

________________________________
De: Profesor IAP <notifications@github.com>
Enviado: martes, 13 de diciembre de 2016 17:22:26
Para: profeIAP/Documentacion
Cc: felixgp00; State change
Asunto: Re: [profeIAP/Documentacion] Grabar cómo añadir contactos a un grupo (#2)


Reopened #2<https://github.com/profeIAP/Documentacion/issues/2>.

-

**Comment by profeIAP** [comment]
En clase hemos visto por qué te fallaba la calidad del vídeo.

Aquí te dejo cómo se pueden incluir enlaces en un comentario de la tarea

![captura de pantalla de 2016-12-16 12 33 29](https://cloud.githubusercontent.com/assets/16881846/21261611/d865c4ec-c38c-11e6-88ba-621a62d8436d.png)

**Comment by laury11** [comment]
le asigno esto a alicia valle hasta que pueda entrar en su cuenta

**Comment by profeIAP** [comment]
Lo siento @laury11 pero esta tarea pertenece a @felixgp00, quito tu asignación

**Comment by profeIAP** [comment]
Y aquí está [el vídeo de Felix](https://drive.google.com/open?id=0B1or4uFFvPJ-bkVGcU9NQkM0MW8)

**Comment by profeIAP** [comment]
Ha quedado bien aunque deberías haber evitado poner contactos reales 😳
