### ISSUE TITLE
Grabar cómo eliminar ruido de una pista de audio

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#20]
Crear un vídeo en el que se muestre cómo eliminar los ruidos de fondo de nuestras grabaciones de audio.

Aunque se han perdido las imágenes que ilustraban el proceso, puede resultar de utilidad [el siguiente artículo](https://andalinux.wordpress.com/2008/10/15/eliminar-ruido-de-una-grabacion-de-audio-con-audacity/)

**Comment by Frangamboag** [comment]
.

**Comment by profeIAP** [comment]
Fran, si quieres la tarea asígnatela ;)

El ser el primero en poner un comentario no supone ningún privilegio sobre ella

**Comment by Frangamboag** [comment]
Tarea hecha, [https://youtu.be/8b6t7TmGyL4](url)
