### ISSUE TITLE
Grabar cómo obtener los FPS de cualquier vídeo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#202]
Crear un vídeo en el que se muestre cómo obtener los Frames Per Second (FPS) de algún vídeo que tengas abierto.

![captura de pantalla de 2017-01-24 19-35-08](https://cloud.githubusercontent.com/assets/16881846/22261193/48914522-e26c-11e6-9897-654d4d46bd21.png)

**Comment by manu77arahal** [comment]
Maestro aquí esta [el video](https://drive.google.com/open?id=0ByFm-qTFuQksYzRiNUMzQkowRVU)

**Comment by profeIAP** [comment]
Lo abro hasta que pueda revisarlo (yo me encargo de cerrarlo si procede)
Gracias

**Comment by profeIAP** [comment]
Fantástico, buen trabajo Manu
