### ISSUE TITLE
Grabar cómo mostrar las versiones de un documento en Google Docs

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#204]
Crear un vídeo en el que se muestre cómo podemos ver todos los cambios realizados en un documento de Google Docs

![captura de pantalla de 2017-01-24 19-38-19](https://cloud.githubusercontent.com/assets/16881846/22261337/d3c7a9c4-e26c-11e6-9ee2-f6ea6e4d7db5.jpg)

**Comment by elena182001** [comment]
Maestro ,soy Elena .[Aquí te dejo el video]https://drive.google.com/open?id=0B_TvbmLEFXTVb1dEcktBX3RyczA)

**Comment by elena182001** [comment]
Hola maestro, soy Elena Saborido. [Aquí tienes el video](https://drive.google.com/open?id=0B_TvbmLEFXTVb1dEcktBX3RyczA)

**Comment by profeIAP** [comment]
Ha quedado genial Elena, muchas gracias
