### ISSUE TITLE
Narrar cómo mostrar las versiones de un documento en Google Docs

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#209]
Describir el proceso seguido en el vídeo de la tarea #204

**Comment by elena182001** [comment]
Maestro , soy Elena .[Aquí  te dejo el video](https://drive.google.com/open?id=0B_TvbmLEFXTVb1dEcktBX3RyczA)

**Comment by elena182001** [comment]
Hola maestro, soy Elena Saborido. [Aquí tienes el audio](https://drive.google.com/open?id=0B_TvbmLEFXTVSTlnRk5wZHBCVmM)

**Comment by profeIAP** [comment]
Se escucha muy claro pero:

1. No termina de cuadrar lo que se ve con lo que se oye
1. Sería interesante hacer mención al margen derecho donde aparece la fecha y hora de los distintos cambios.

Agradecería se mejorase

**Comment by elena182001** [comment]
Maestro soy elena , aquí te dejo [el audio](https://drive.google.com/open?id=0B_TvbmLEFXTVb3E4Z01XRlptWkE) de nuevo .

**Comment by profeIAP** [comment]
Tu usuario (elena182001) te ha delatado Elena, sabíamos que eras tú (no es necesario que te presentes pero se te agradece la deferencia)

El fichero que has enlazado ni tiene extensión (mp3, mp4a, ...) ni puede abrirse con los reproductores de sonido habituales. ¿Te importaría corregirlo?

Gracias

**Comment by elena182001** [comment]
Maestro , aquí te dejo de nuevo el[ audio](https://drive.google.com/open?id=0B_TvbmLEFXTVU25pWjgwSkU3cDg)

**Comment by profeIAP** [comment]
Gracias Elena pero no se oye nada en el nuevo fichero que has enlazado.
Llama la atención que el tamaño es pequeño para ser una grabación de voz.

**Comment by elena182001** [comment]
maestro, aquí te dejo de nuevo [el audio](https://drive.google.com/open?id=0B_TvbmLEFXTVU25pWjgwSkU3cDg) otra vez.

**Comment by profeIAP** [comment]
Pues me temo Elena que sigue sin poder oírse el fichero que has subido.
Observo que vuelve a tener 18,8KB ¿segura que has subido el fichero correcto?

**Comment by elena182001** [comment]
Aqui  te dejo [el audio ](https://drive.google.com/open?id=0B_TvbmLEFXTVOUx0U1k0N0JtTUU)de nuevo maestro, aver si se escucha ya :()

**Comment by profeIAP** [comment]
Perfectamente, muchas gracias Elena.
Vas un poco acelerada pero el vídeo es tan corto que entiendo que lo tengas que hacer así.
Creía recordar que había algo más grabado 😅
Damos por terminada la tarea, gracias.
