### ISSUE TITLE
Narrar cómo crear un grupo de contactos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#21]
Describir el proceso seguido en el vídeo de la tarea #1

**Comment by Frangamboag** [comment]
Tarea hecha, [https://youtu.be/CdDWA4Wf4ec](url)

**Comment by profeIAP** [comment]
El [audio](https://drive.google.com/open?id=0B1or4uFFvPJ-RERIWHpjU0pERWJYaDVFSjd3T0VuS3hSQVdF) de la tarea
