### ISSUE TITLE
Grabar cómo cerrar tareas en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#246]
Crear un vídeo en el que se muestre cómo cerrar una tarea en GitHub (requisito que debe cumplir todo aquel que desee se le corrija su trabajo :) )

**Comment by benjigar** [comment]
El [vídeo](https://drive.google.com/open?id=0B1Ji95nqC8V8d0FFTEx3MkpQYW8)

**Comment by profeIAP** [comment]
Muchísimas gracias Benjamín.
Me ha encantado el detalle de buscar las tareas que tienes cerradas 👍
