### ISSUE TITLE
Grabar cómo descargar cualquier vídeo usando Video DownloadHelper

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#247]
Crear un vídeo en el que se muestre cómo descargar vídeos de internet [usando la extensión Video DownloadHelper](https://addons.mozilla.org/es/firefox/addon/video-downloadhelper/) de Firefox

**Comment by gabrobtruj** [comment]
maestro el video lo quieres con sonido o sin sonido??

**Comment by profeIAP** [comment]
Salvo que tengas la tarea de narración compañera a ésta, sin audio.

**Comment by AnaGonzales12** [comment]
Te dejo aqui la grabacion de [la tarea 
](https://drive.google.com/open?id=0B04oTFHiDpAkT0g0eEpnSXBSczQ)

**Comment by profeIAP** [comment]
Está bastante bien Ana pero los vídeos deben tener, como mínimo, una resolución de 720p.
En cuanto a enlazar desde Github, puedes consultar la tarea #46

**Comment by AnaGonzales12** [comment]
Maestro, en esta tarea tengo un 0?

**Comment by profeIAP** [comment]
Por desgracia sí... sólo has realizado un envío y no es correcta la tarea por lo que no puedo darla por buena.

**Comment by AnaGonzales12** [comment]
Maestro aqui te dejo la tarea para poder recuperar la asignatura del trimestre pasado.
Te dejo aqui dicha[ tarea](https://drive.google.com/open?id=0B04oTFHiDpAkajlLTzZFWjFSTGc)

**Comment by profeIAP** [comment]
Genial, gracias Ana pero entiendo que lo has grabado en uno de los portátiles de alumno (de los "verdes") y la resolución no llega a los 720p que tenemos establecida para las grabaciones por lo que no puedo dar por buena la tarea. Si lo prefieres, pídeme cita previa y lo hablamos en clase ¿te parece? 👍

**Comment by AnaGonzales12** [comment]
Venga vale de acuerdo!! El próximo día lo hablamos en clase!! Gracias
maestro

**Comment by AnaGonzales12** [comment]
[Aqui](https://drive.google.com/open?id=0B04oTFHiDpAkRjRzQndURTVRTjQ) tienes grabado en 720p, haber si ahora tenemos suerte!!

**Comment by profeIAP** [comment]
Ahora sí Ana, buen trabajo 👍
