### ISSUE TITLE
Grabar cómo activar el bloqueo de publicidad en Firefox

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#248]
Crear un vídeo en el que se muestre cómo evitar ser bombardeados con publicidad en Firefox utilizando el antiadware/antipopup incluido en Firefox

![captura de pantalla de 2017-01-30 17-37-21](https://cloud.githubusercontent.com/assets/16881846/22431715/d250569a-e712-11e6-838e-7cca764deb9a.png)

**Comment by ghost** [comment]
[Aquí video](https://drive.google.com/open?id=0B3GMW7GMWk9MQlpoM3pGVVFoREU)

**Comment by profeIAP** [comment]
Muchísimas gracias, D. Francisco.

Puedo comprobar que al final pudo recuperar el vídeo borrado de la papelera (espero que no lo grabase nuevamente tras el "incidente" ¿¡¿verdad?!?)

Esperaba que hubiese utilizado "Blocks Ads" pues, aunque adBlock es el referente y el más conocido, en la imagen que ilustra la descripción de la tarea, es el que se recomendaba.
