### ISSUE TITLE
Grabar cómo se entregan las tareas usando GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#251]
Crear un vídeo en el que se muestre cuál es el proceso completo que debe seguirse para dar por finalizada nuestra tarea de GitHub.

Debe contemplar:
1. subir nuestro trabajo a la carpeta compartida de Drive (vídeo o audio da igual)
1. obtener el enlace compartido del fichero subido
1. crear el comentario en la tarea de GitHub utilizando el enlace del paso anterior
1. cerrar la tarea

Esta tarea surge por recomendación de @Frangamboag (al César lo que es del César, gracias) porque sois varios los que le pedís lo mismo y se ha detectado la _necesidad_ de explicarlo.

**Agradecería** que me comentéis (email o en persona) todas aquellas cosas que os piden vuestros compañeros porque no saben hacerlo... sería interesante "retenerlo" aquí 👍

**Comment by humanes14** [comment]
Tarea acabada [aqui](https://drive.google.com/file/d/0B0jFhmGL6h-AVUhGR1ZzbThJbjA/view?usp=sharing)

**Comment by humanes14** [comment]
[Grabado](https://drive.google.com/file/d/0B0jFhmGL6h-AQ3RSUFVVSkxiN1k/view?usp=sharing)

**Comment by profeIAP** [comment]
Aunque podrías haberlo hecho de una forma mucho más sencilla para tus compañeros se puede decir que te ha quedado muy bien, ¡gracias Jorge!
