### ISSUE TITLE
Grabar cómo convertir a MP3 cualquier fichero de sonido

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#252]
Crear un vídeo en el que se muestre cómo, utilizando Audacity se puede convertir cualquier fichero de sonido al formato MP3 reproducible, con menos problemas, en cualquier sistema.

Agradecer a @elenashp (creo recordar que fuíste tú, te agradecería me corrigieses si no es así) el haberme dado la idea.

**Comment by irene32** [comment]
[aqui](https://drive.google.com/file/d/0B2jsfPDHucovWjBCbTYwNldLcEU/view?usp=sharing) esta la grabacion de como convertir a mp3 cualquier fichero de sonido

**Comment by profeIAP** [comment]
Debes estar sorprendida hasta tú... ¿¡¿lo has logrado a la primera?!? (le vamos a tener que hacer un monumento a @Frangamboag 😂)
