### ISSUE TITLE
Narrar cómo convertir a MP3 cualquier fichero de sonido

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#255]
Describir el proceso seguido en el vídeo de la tarea #252

**Comment by JesusLG11** [comment]
Narracion como convertir a MP3 cualquier fichero de sonido,  by: Jesus lobato
https://drive.google.com/file/d/0B2TOV4Ypk2XLVE1YdWdvb1J6bUk/view?usp=sharing

**Comment by profeIAP** [comment]
Fantástico Jesús pero recuerda que, para poder cerrar las tareas, se deben ocultar los enlaces a ficheros de los comentarios 😏

**Comment by JesusLG11** [comment]
[narracion como convertir a mp3 cualquier fichero](url)

**Comment by JesusLG11** [comment]
[Narracion como convertir a MP3 cualquier fichero de sonido, by: Jesus lobato`](https://drive.google.com/file/d/0B2TOV4Ypk2XLVE1YdWdvb1J6bUk/view?usp=sharing)

**Comment by JesusLG11** [comment]
Ya está solucionado,gracias.Buenas noches maestro

**Comment by profeIAP** [comment]
Perfecto, gracias
