### ISSUE TITLE
Narrar cómo cerrar la sesión en GMail

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#257]
Describir el proceso seguido en el vídeo de la tarea #250

**Comment by prainplayx** [comment]
Aqui el [audio](https://drive.google.com/open?id=0B9lsiGwGvCMTMnhJdElKNV9kdDA)

**Comment by profeIAP** [comment]
Genial y encima procurando hacer una buena dicción (se agradece "monstruo" 👍)
