### ISSUE TITLE
Narrar cómo activar el bloqueo de publicidad en Firefox

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#259]
Describir el proceso seguido en el vídeo de la tarea #248

**Comment by illanes16** [comment]
[](url)

**Comment by illanes16** [comment]
aquí está [el audio](https://drive.google.com/open?id=0B_NCVxOSdbWjbll3TDNxWEEzSms)

**Comment by profeIAP** [comment]
Te sobra bastante vídeo pero el "editor" del mismo tiene la libertad de cortar todo lo que sobra... gracias Sergio
