### ISSUE TITLE
Narrar cómo compartir una carpeta en Guadalinex

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#26]
Describir el proceso seguido en el vídeo de la tarea #6

**Comment by Jesusbg19** [comment]
hecho [](url)https://drive.google.com/file/d/0Bym9m5PPnKP-SExHMEV2bm81d1U/view?usp=sharing

**Comment by profeIAP** [comment]
Jesús, hay algo que no me "cuadra": ¿por qué hablas en el fichero de compartir ficheros de windows usando Samba?
¿Es posible que hayas enlazado el fichero que no es?

**Otra cosa**: para dar por cerrada la tarea necesito que ocultes el enlace que has puesto en tu último comentario, gracias.

**Comment by maria99mh** [comment]
Aqui tienes [el audio]https://drive.google.com/open?id=0BxEbuEKZS9TMcmhuMi1SRmxlMndLTXNCdEVmSXZvUHRZNVFr(url)

**Comment by maria99mh** [comment]
Aqui tienes [el audio](https://drive.google.com/open?id=0BxEbuEKZS9TMcmhuMi1SRmxlMndLTXNCdEVmSXZvUHRZNVFr)

**Comment by profeIAP** [comment]
Aunque va todo el proceso algo acelerado (el vídeo tiene gran parte de la culpa) se puede considerar que está bien... ya veremos cómo le va a quien se atreva a montar el vídeo final ;)
