### ISSUE TITLE
Narrar cómo cerrar tareas en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#261]
Describir el proceso seguido en el vídeo de la tarea #246

**Comment by mariateresapg01** [comment]
Listo! Te dejo el [enlace](https://drive.google.com/open?id=0B77IAfhm-w9pYkxXN0xjeXBsclE)

**Comment by profeIAP** [comment]
La "alumna cuántica" ataca de nuevo... 😂

Algunas observaciones:

1. Aunque me ha encantado lo del "recuadrito" hubiese quedado mejor decir "botón" (que se note que tienes destreza lingüística, no le pega a ud. éso 😉)
1. No indicas lo que está haciendo al final del vídeo Benjamín y sería de agradecer pues como comento al aceptar su tarea (casi 4h después de que ud. haya grabado este audio 😂) me parece una gran aportación.

Podemos:

1. Parchear los fragmentos de audio "mejorables"
1. Volver a grabarlo íntegramente

Ud. decide qué considera más oportuno (o incluso ya tiene la respuesta antes de que haya formulado la pregunta anterior 🤔)

**Comment by mariateresapg01** [comment]
Ahora sí! Te dejo[ el enlace](https://drive.google.com/file/d/0B77IAfhm-w9pYkxXN0xjeXBsclE/view?usp=sharing)

**Comment by profeIAP** [comment]
¡Qué chulo te ha quedado! ¡Gracias Teresa!

**Comment by benjigar** [comment]
El [audio](https://drive.google.com/open?id=0B1Ji95nqC8V8QVR1bGtCa2tZNXM) del vídeo

**Comment by profeIAP** [comment]
@benjigar esta tarea pertenece a Teresa y ya ha sido cerrada (y validada)...
