### ISSUE TITLE
Narrar cómo compartir una carpeta en Windows XP

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#27]
Describir el proceso seguido en el vídeo de la tarea #7

**Comment by gabrircurz** [comment]
Aqui tienes [la narracion](https://drive.google.com/open?id=0BwusAkelVplkTW5NdUQ5Wi1nUlE)

**Comment by gabrircurz** [comment]
Aqui tienes [el audio](https://drive.google.com/open?id=0B4BWP5Tsm7rXeWFtWkJOVldReFE)

**Comment by profeIAP** [comment]
Te ha quedado muy bien Gabriel pero es demasiado grande el desfase entre lo que dices y lo que se ve.

Igual vas a tener que hacer la edición final (la tarea que nos falta para cerrar este bloque) para alargar los "fotogramas" para que voz y vídeo funcionen.

Éso o grabar de otro modo el audio para que coincida con lo que se está viendo.

Quedo a la espera de que tomes una decisión ;)

**Comment by gabrircurz** [comment]
Aqui tienes [el audio](https://drive.google.com/open?id=0BwusAkelVplkeGZFMWo5VnowcU0l)

**Comment by gabrircurz** [comment]
Aqui tienes [el audio](https://drive.google.com/open?id=0BwusAkelVplkeGZFMWo5VnowcU0)

**Comment by profeIAP** [comment]
Mejor la narración que la grabación... acabo de ver que se nota cómo sale un poco del menú que se utiliza para parar la grabación 😒
