### ISSUE TITLE
Editar vídeo cómo convertir a MP3 cualquier fichero de sonido

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#280]
Usando PiTiVi, editar el vídeo de la tarea #252 de modo que: 
1. Se eliminen todas las partes que sobran (como p.e. el final en el que se ve cómo su autor para recordMyDesktop)
1. Se incluya la narración asociada a dicha tarea.
1. Se elimine el sonido de fondo que incluye el vídeo original (para evitar que se solape con la narración). De especial utilidad te resultará el vídeo generado en la tarea #52

**Comment by JesusLG11** [comment]
Edición de como convertir a MP3 cualquier fichero de sonido by, Jesús Lobato

https://drive.google.com/file/d/0B2TOV4Ypk2XLTkFjQ01ELW5GOE0/view?usp=sharing

**Comment by profeIAP** [comment]
Genial, aunque con un pequeño desfase entre lo que dices y haces... p.e. "pulsamos aceptar" cuando hace un siglo que lo has pulsado.

No queda mal del todo pero raya... no obstante lo daremos por bueno puesto que el resultado es muy bueno en general.

Buen trabajo Jesús, gracias.

**NOTA:** oculta ese enlace para que se tenga en cuenta, como terminada, la tarea 😏

**Comment by JesusLG11** [comment]
[Edición de como convertir a MP3 cualquier fichero de sonido by, Jesús Lobato](https://drive.google.com/file/d/0B2TOV4Ypk2XLTkFjQ01ELW5GOE0/view?usp=sharing)

**Comment by JesusLG11** [comment]
Ya está solucionado,gracias.Buenas noches maestro

**Comment by profeIAP** [comment]
Simplemente espectacular, gracias Jesús
