### ISSUE TITLE
Grabar cómo quitar un contacto de un grupo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#3]
Crear un vídeo en el que se muestre cómo hacer que un contacto deje de pertenecer a un grupo determiando.

**OJO**: el contacto no debe eliminarse de nuestra agenda, sólo quitarlo del grupo en el que estaba

**Comment by GonzaloVera4** [comment]
Maestro ya he terminado la tarea aquí está el enlace para ver el video:

https://drive.google.com/open?id=0B1u-y44k9UJ3cHRZVFpUWktEU1E

**Comment by profeIAP** [comment]
Está francamente bien, Gonzalo pero podría estar mejor

+ El vídeo debería comenzar en la bandeja de entrada de GMail y no en la tarea de GitHub (no hace falta volver a grabarlo, basta con cortar lo que no sirve usando PiTiVi)
+ Agradecería se ocultase el enlace al vídeo en tu comentario anterior (queda feo ver la url al "desnudo")

Sigue así Gonzalo

**Comment by GonzaloVera4** [comment]
[Ya está corregida la tarea y todo como me dijiste.](https://drive.google.com/open?id=0B1u-y44k9UJ3enpfaXYyLVZDZjQ)

**Comment by profeIAP** [comment]
Perfecto Gonzalo, ¡muy buen trabajo!
Gracias
