### ISSUE TITLE
Narrar cómo recortar una secuencia de vídeo en PiTiVi

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#31]
Describir el proceso seguido en el vídeo de la tarea #11

**Comment by albavera** [comment]
Esta es la [tarea](https://drive.google.com/file/d/0BwM4Yi3Ht1DzTXNSb3VvS0RwM0U/view?usp=sharing)

**Comment by profeIAP** [comment]
Está perfecto, muchísimas gracias Alba
