### ISSUE TITLE
como editar un comentario

### ISSUE THREAD

**Issue by ersuarez** [profeIAP/Documentacion#311]
como editar un comentario

_Originally posted by @ersuarez in https://github.com/profeIAP/Documentacion/issues/245#issuecomment-452682063_

**Comment by profeIAP** [comment]
@ersuarez, que edites comentarios me parece bien pero que crees nuevas tareas (que luego no pueden eliminarse porque GitHub no lo permite) ya me gusta menos.

Si no tienes claro cuál es el objetivo de la tarea #245, pide cita y te indico en qué consiste.

**Comment by ersuarez** [comment]
No mastro lo que pasó fue que no me dejaba editar los comentarios (el
porque ya no lo se) y total que la lie tocando y cree las tareas aunque ya
las e bloqueado

**Comment by profeIAP** [comment]
No te preocupes (pero no crees más tareas, please)
Si te sigue dando problemas el editar comentarios, dímelo en clase y lo vemos
