### ISSUE TITLE
Grabar cómo ocultar información en un vídeo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#315]
Sería interesante explicar cómo se puede ocultar información "sensible" (correos electrónicos, emails en la bandeja de entrada, ...) que aparezcan en las grabaciones que hacemos en clase.

En base a [la información que encontrarás en el siguiente artículo](https://andalinux.wordpress.com/2018/03/06/montaje-de-video-con-kdenlive-creando-una-mascara-para-ocultar-la-identidad-de-una-persona/) (o cualquier otro vídeo que encuentre en Youtube), deberemos mostrar cómo ocultar (pixelar) dicha información

**Comment by angela3301** [comment]
¿?

**Comment by profeIAP** [comment]
No preguntes Ángela, parece que Ana se ha hecho "lío" XD
