### ISSUE TITLE
Narrar cómo registrar sonidos con Audacity

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#33]
Describir el proceso seguido en el vídeo de la tarea #13

**Comment by FraniBL** [comment]
[Hecho](https://drive.google.com/file/d/0B5qdPOBTbGERSVpwM1cxOVdrREU/view?usp=sharing)

**Comment by FraniBL** [comment]
[Hecho](https://drive.google.com/file/d/0B5qdPOBTbGERcnRyYWRRdmxPZVk/view?usp=sharing)

**Comment by profeIAP** [comment]
La grabación suena espectacularmente bien y vas muy tranquilo narrando.

Lo único que me ha sorprendido es que llames a los botones:

1. Círculo rojo (botón grabar) y
1. Cuadrado amarillo (botón parar)

Me parece muy fuerte dejarlo así pues no termina de ser algo "pro" ¿qué quieres que hagamos? (dejarlo así o arreglarlo)

**Comment by FraniBL** [comment]
[ACABADOOOO](https://drive.google.com/file/d/0B5qdPOBTbGERWEhXSTVRdGxzVG8/view?usp=sharing)

**Comment by profeIAP** [comment]
Se nota que como ya "controlas" más Audacity y su "botonera" XD vas algo acelerado y no termina de cuadrar (en el tiempo) lo que cuentas con lo que se está viendo realmente.

Observo que tienes asignada la tarea de edición (#139) por lo que recae sobre tus hombros hacer que vaya bien.

Si lo dejas tal y como está, tendrás que "hilar" algo más fino (pero también aprenderás más) ;)
