### ISSUE TITLE
Narrar cómo unir dos pistas de audio en Audacity

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#34]
Describir el proceso seguido en el vídeo de la tarea #14

**Comment by ivanhumanes20** [comment]
Maestro ya he hecho la tarea
https://drive.google.com/drive/folders/0B1or4uFFvPJ-U2c4RGVpMUNPSU0

**Comment by profeIAP** [comment]
Un par de cosas para poder dar por buena la tarea:

1. Has enlazado el directorio en el que está el audio (en lugar del fichero de sonido directamente)
1. No has ocultado el enlace en el comentario anterior (queda feo y quiero que aprendas ;) )

**Comment by profeIAP** [comment]
Ivan ¿realmente estás describiendo el vídeo grabado por @Frangamboag en la tarea #14?

**Comment by ivanhumanes20** [comment]
Esta es la [tarea](https://drive.google.com/file/d/0B3QPZY-XeQ_ecWN3djdmOFdOUnM/view?usp=sharing)

**Comment by profeIAP** [comment]
Qué mareo... yo no me he enterado de nada con tanta canción arriba y abajo, así que sospecho que tus compañeros tampoco.

Si te parece (y lo necesitas), lo hablamos

**Comment by ivanhumanes20** [comment]
Esta ya es la [buena](https://drive.google.com/file/d/0B3QPZY-XeQ_eT0gwSXNTWUNycFE/view?usp=sharing)

**Comment by profeIAP** [comment]
Pero, sin embargo, no me cuadran los tiempos ¿? (estás hablando de exportar a mp3 las dos pistas cuando todavía está Fran escuchando el resultado)

**Comment by ivanhumanes20** [comment]
Pero maestro al editar el vídeo lo he arreglado,¿te lo adjunto en la tarea
de narrar?

**Comment by ivanhumanes20** [comment]
[Tarea](https://drive.google.com/file/d/0B3QPZY-XeQ_eT0gwSXNTWUNycFE/view?usp=sharing) terminada

El problema que me dices lo soluciono en el [video editado](https://drive.google.com/file/d/0B3QPZY-XeQ_eVl85d3hLQnE5MlU/view?usp=sharing)

**Comment by profeIAP** [comment]
Genial, buen trabajo.
Muchas gracias Iván
