### ISSUE TITLE
Narrar cómo eliminar un fragmento de audio con Audacity

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#35]
Describir el proceso seguido en el vídeo de la tarea #15

**Comment by Ezki14** [comment]
Hecho (https://drive.google.com/drive/folders/0B1or4uFFvPJ-U2c4RGVpMUNPSU0)

**Comment by profeIAP** [comment]
Imagino que estará bien pero necesito:

1. Que enlaces el fichero de audio correcto (en lugar de la carpeta como has hecho arriba)
1. Que ocultes el enlace (queda feo y quiero que aprendas a hacerlo)
1. No olvides cerrar las tareas (botón "Close")

**Comment by Ezki14** [comment]
ACABADA https://drive.google.com/file/d/0B0QdTXKv7lZ5SEJtUExsaDJsNFE/view?usp=sharing

**Comment by Ezki14** [comment]
HECHO

https://drive.google.com/file/d/0B0QdTXKv7lZ5SEJtUExsaDJsNFE/view

https://github.com/profeIAP/Documentacion/issues/35

**Comment by profeIAP** [comment]
Ezequiel... recuerda que los enlaces se deben ocultar en el texto (queda feo verlos)
El audio no está mal del todo pero me llama la atención que es muchísimo más corto que el vídeo ¿algún motivo "lógico"?

**Comment by profeIAP** [comment]
Está todo perfecto menos las "guarrerías" de enlaces que has dejado por ahí... sigo esperando a que lo ocultes TODO ;)

**Comment by Ezki14** [comment]
[Tarea hecha](https://drive.google.com/file/d/0B0QdTXKv7lZ5SEJtUExsaDJsNFE/view?usp=sharing)

**Comment by profeIAP** [comment]
🎼 Escóndelos, escóndelos, escóndelos...

**Comment by profeIAP** [comment]
Mientras no ocultes y cierres la tarea no te pondré la nota que te mereces ;)

**Comment by profeIAP** [comment]
Perfecto Ezequiel, gracias.
Muy buen trabajo, enhorabuena,
