### ISSUE TITLE
Narrar cómo añadir una pista de audio en PiTiVi 

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#36]
Describir el proceso seguido en el vídeo de la tarea #17

**Comment by Carjop** [comment]
[Audio](https://drive.google.com/open?id=0B8tTRlqZUkjnbVVMbTFRQUg3Sm8)

**Comment by profeIAP** [comment]
Creo que no me estoy enterando bien... añadir pistas de audio en ¿¡¿Movie Maker?!? 😳
Sospecho que esta mañana no debí entender lo que querías hacer, creí que me estabas hablando de hacer **la edición** con Movie Maker no que fueses a explicar cómo se hace en una herramienta de Moco$oft que no vamos a tener NUNCA (y cuando digo NUNCA es NUNCA) en el aula.

Palabra de "talibán linuxero"

![](https://elbinario.net/wp-content/uploads/2015/05/linuxtaliban.jpg)

**Comment by Carjop** [comment]
[https://drive.google.com/open?id=0B8tTRlqZUkjnVmJ6MXd0Smo4X2c](Audio)

**Comment by Carjop** [comment]
[Audio](https://drive.google.com/open?id=0B8tTRlqZUkjnVmJ6MXd0Smo4X2c)

**Comment by profeIAP** [comment]
Ahora sí, perfecto
