### ISSUE TITLE
Grabar cómo extraer un fotograma de un vídeo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#371]
La idea es poder extraer la imagen (fotograma) de un segundo determinado de un vídeo utilizando PiTiVi o cualquier herramienta (se cataloga como _reto_ por requerir investigación por tu parte) con la que resulte lo más sencillo posible (o asumible que cualquiera, por poco nivel que tenga, con tus explicaciones pueda realizarlo)

**Comment by saramarfer** [comment]
Doy por finalizada esta tarea.

**Comment by profeIAP** [comment]
Y lo has hecho estupendamente bien, buen trabajo Sara 👍🏻

**Comment by profeIAP** [comment]
Bueno corrijo: estupendamente bien menos cerrar la tarea 😏
