### ISSUE TITLE
Narrar cómo eliminar ruido de una pista de audio

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#39]
Describir el proceso seguido en el vídeo de la tarea #20

**Comment by Frangamboag** [comment]
Tarea hecha, [https://youtu.be/Y8Qbzl6fqUY](url)

**Comment by profeIAP** [comment]
Me parece bien reutilizar el trabajo de otros y pase que tenga el audio en inglés (como no es nativo del Bronx se le entiende bien) pero 

1. te has apropiado el trabajo de alguien
1. desconocemos la licencia con la que ha compartido el material (importante para ver si podemos poner nuestra cortinilla y "doblar" lo que hace al castellano)

La primera (si la licencia lo permite) la podemos arreglar dándole los créditos al autor original y no poniendo ni nuestro logo ni nuestra cortinilla pero debemos documentarnos previamente

**Comment by profeIAP** [comment]
Estoy obviando que la tarea es NARRAR (grabar en un fichero de audio las instrucciones pertinentes) que no GRABAR y sí, soy consciente que se podría extraer en mp3 el audio del vídeo que has compartido en Youtube ;)

**NOTA: ** el resto de tareas que has cerrado tienen el mismo "problema" (por lo que deberemos tomar una decisión y aplicarla a todas las tareas del mismo modo) . Si te parece (y nos dejan) lo hablamos en clase.

El resto de "colaboradores" puede expresar (si lo desea) su opinión al respecto en los comentarios de esta tarea. Será interesante y nos servirá para ir cogiendo confianza con el gestor de tareas de Github ;)

**Comment by Frangamboag** [comment]
No entiendo el primer comentario, ¿cómo que me he apropiado del trabajo de alguien? 
PD: Este es de eliminar ruido de una pista (lo digo por lo de la cortinilla)

**Comment by profeIAP** [comment]
¿Eres el autor de la grabación de Youtube que has enlazado?

**Comment by Frangamboag** [comment]
Sí, lo hago en inglés porque me parece muy de tutorial latino hacerlo en español, y así de paso hago algo con el inglés (I'm bilingual)

**Comment by profeIAP** [comment]
LOL!! Pareces profesional (y me consta que lo eres, te lo he puesto demasiado "fácil")

Me he dado cuenta del detalle de la fecha y la hora (la barra de windows y su feísimo logo me impedían mirar más allá del botón de inicio XP) utilizando el vídeo para unas pruebas con Google Sites (no descarto recopilar con él todo el trabajo que realicéis para que resulte más sencillo localizar el material al resto de compañeros de clase)

Creo que te voy a tener que "convalidar" la parte de multimedia (y/o "pagarte" por el trabajo realizado) a pesar de que juegas con ventaja XD

**Comment by profeIAP** [comment]
Ya te buscaré (una vez más pero por primera vez en este curso) algún "entretenimiento" que te haga aprovechar el tiempo [ en lugar de que nosotros aprovechemos el tuyo ;) ] para aprender

**Comment by profeIAP** [comment]
La tarea realmente la he liberado yo (aunque lo hice con la cuenta de @maria99mh)

Queda disponible para que cualquiera "doble" la grabación en inglés de @Frangamboag al "cristiano castellano" :)

**Comment by humanes14** [comment]
[Acabado maestro](https://drive.google.com/file/d/0B0jFhmGL6h-ATWNSQ0MySTNJcVk/view?usp=sharing)

**Comment by profeIAP** [comment]
Apenas coincide y dejas huecos sin narrar tanto al comienzo como al final... veo complicado que el compañero que decida editar logre cuadrarlo todo correctamente.

Como veo que eres tú el encargado de la edición, lo daré por bueno esperando logres el resultado deseado en la edición 👍
