### ISSUE TITLE
Grabar cómo mostrar y ocultar la ayuda de Google Sheets

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#394]
Deberás explicar a tus compañeros cómo se oculta la ayuda de Google Sheets para una función
![image](https://user-images.githubusercontent.com/16881846/74026754-1d68e080-49a7-11ea-90d5-5e6ee14502a7.png)
Cómo quitar el "cartelón" de la ayuda
![image](https://user-images.githubusercontent.com/16881846/74026796-2eb1ed00-49a7-11ea-907e-b46ce66523b1.png)
y cómo hacer que ocupe menos espacio
![image](https://user-images.githubusercontent.com/16881846/74026814-3bcedc00-49a7-11ea-9125-64d59f953d6f.png)

**Comment by Jose-bot211** [comment]
Tarea resuelta y entregada, con un poco de retraso...
