### ISSUE TITLE
Grabar cómo clonar un repositorio de Github

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#397]
Explicar a los compañeros cómo se clona[ un repositorio en Github](https://github.com/profeIAP/testGIT) en nuestro ordenador para poder colaborar en él
![image](https://user-images.githubusercontent.com/16881846/74140511-7b8b0300-4bf5-11ea-92fd-0c630b31a42e.png)

**Comment by profeIAP** [comment]
¡Qué velocidad! ¿Segura que has podido grabar y terminar la tarea?
¿Con audio y todo?
La abro mientras aclaramos la duda ¿te parece?

**Comment by nerea364** [comment]
No todavía no lo he echo pero le habre dado sin querer

**Comment by nerea364** [comment]
Doy por finalizada esta tarea(aquí te dejo el [video)](https://drive.google.com/file/d/1X9v3g22ACkvTPpqZ-bbGciEAyLkD9aAW/view?usp=sharing)
