### ISSUE TITLE
Explicar cómo obtener el código de acceso a nuestro AnyDesk

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#405]
Es importante enseñar a otros compañeros cómo se obtiene el código (empieza de forma que se vea cómo abres AnyDesk para los más despistados) que deben proporcionar al profesor para que se conecte remotamente a su equipo y le pueda ayudar

![image](https://user-images.githubusercontent.com/16881846/99710263-9fdb1080-2aa0-11eb-8101-2f1fa50a45e6.png)

**Comment by edubalrio** [comment]
Maestro, ya esta la tarea realizada y entregada por classroom.
