### ISSUE TITLE
Explicar cómo crear "fake news"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#409]
Mostrar a los compañeros cómo modificar cualquier web para crear una noticia falsa
![imagen](https://user-images.githubusercontent.com/16881846/99802503-1a0aa400-2b38-11eb-831c-0246b619beb9.png)

**Comment by p4b10-12** [comment]
> Mostrar a los compañeros cómo modificar cualquier web para crear una noticia falsa
> ![imagen](https://user-images.githubusercontent.com/16881846/99802503-1a0aa400-2b38-11eb-831c-0246b619beb9.png)

**Comment by profeIAP** [comment]
@p4b10-12 elimino tu comentario por ser le mismo que he puesto yo y no aportar nada: la idea es eliminar "ruido" :wink:
