### ISSUE TITLE
Explicar cómo crear perfiles en shotCut

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#416]
Deberás explicar cómo crear un perfil de vídeo adaptado a nuestros portátiles (en concreto con resolución 1366x768 píxeles)

**Comment by RcRamses4** [comment]
Tiene que ser un ordenador del instituto o puede ser uno de casa?

**Comment by profeIAP** [comment]
Esta se deja hacerla sin problemas en casa 👍🏻

**Comment by RcRamses4** [comment]
Maestro es shotcup o openshot? Aver si te mas equivocao escribiendo que yo no encuentro ningun perfil en shotcut XD

**Comment by RcRamses4** [comment]
Pero maestro, es OpenShot o ShotCut? Porque recuerdo que en la clase utilizabamos OpenShot.

**Comment by RcRamses4** [comment]
Doy por finalizada esta tarea

**Comment by profeIAP** [comment]
Pero no la has cerrado... ya me "invito" yo 🤷🏻
