### ISSUE TITLE
Grabar cómo asignarnos una tarea en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#42]
Crear un vídeo en el que se muestre cómo nos podemos asignar una tarea a nosotros mismos.
**NOTA:** Usa una cuenta ficticía de gitHub, no la tuya personal.

**Comment by Frangamboag** [comment]
Can I do it? 😅 I want an straight A (10)😂

**Comment by profeIAP** [comment]
No, you can't do it. 
You **have** your straight A, don't worry (we have to talk) so don't touch it! (it's forbidden)

**Comment by maricarmen01** [comment]
Ya he terminado la tarea de como añadir una tarea a git hub
https://drive.google.com/open?id=0BzuXr9g-7qn3SlRvRk5lYmk2bUk

**Comment by profeIAP** [comment]
Perfecto Mari Carmen, buen trabajo
