### ISSUE TITLE
Narrar cómo asignarnos una tarea en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#43]
Describir el proceso seguido en el vídeo de la tarea #42

**Comment by irene32** [comment]
Aquí está [el trabajo](https://drive.google.com/open?id=0B2jsfPDHucovRS02cUhVTno5ZWM)

**Comment by profeIAP** [comment]
Te queda muy "pro" pero al final de la grabación (cuando hablas del botón derecho para asignar la tarea) no coincide con lo que está haciendo @maricarmen01.

Tienes dos opciones:

1. Describir nuevamente el vídeo completo
1. Grabar sólo la parte que falla y luego ya lo editaremos

En tu mano dejo la elección 😏

**Comment by irene32** [comment]
Aquí está [el audio ](https://drive.google.com/open?id=0B2jsfPDHucovVU12cDR3Ml9TOE0)

**Comment by profeIAP** [comment]
Perfecto Irene salvo por la gran cantidad de ruido que hay de fondo.

Sé que no es culpa tuya (ni te lo achaco) pero agradecería que usases PiTiVi para reducir la excesiva cantidad de ruido que actualmente tiene (así de paso adquieres una nueva "habilidad")

Consulta la tarea #20 para aprender cómo hacerlo

**Comment by irene32** [comment]
aquí esta el[ nuevo fichero sin ruido ](https://drive.google.com/open?id=0B2jsfPDHucovZEpndGZ0MW05c0U)

**Comment by profeIAP** [comment]
Queda raro el "silencio" sepulcral en medio de la grabación (sugiero al que vaya a editar el vídeo final en la tarea #130 que meta música de fondo) pero podría servir.

**Comment by mariateresapg01** [comment]
Maestro, en el audio que está asignado a esta tarea llega un momento en el que el sonido se corta y no vuelve a escucharse nada más. Habría que grabar el audio de nuevo para poder terminar la edición.

**Comment by profeIAP** [comment]
¿Has cogido [el audio de este comentario](https://github.com/profeIAP/Documentacion/issues/43#issuecomment-283904568) o el primero que grabó Irene?

**Comment by profeIAP** [comment]
Perdón abrí la tarea confundido por el comentario de Teresa... pensé que la tarea era suya y luego he comprobado que ha comentado directamente sobre la de Irene 😇

**Comment by mariateresapg01** [comment]
Sí, he cogido el último. Si lo escuchas verás el fallo.

**Comment by profeIAP** [comment]
Aunque es verdad que se corta a la mitad de la grabación, sigo pensando que termina correctamente (enlazo [el audio que he oído](https://drive.google.com/open?id=0B2jsfPDHucovZEpndGZ0MW05c0U)).

Si nos dejan (y como ya tengo los cascos en el cajón) tratamos de oírlo en clase el próximo día si no logras resolverlo por tus medios ¿te parece?
