### ISSUE TITLE
Grabar cómo "soltar" una tarea que tenemos asignada en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#44]
Crear un vídeo en el que se muestre cómo podemos "quitarnos" una tarea que tenemos asignada en GitHub.

**Comment by juankagb00** [comment]
[aquí tienes el enlace](https://drive.google.com/open?id=0BzGsa6imqpYJeFhlOXZON2JIWnM)

**Comment by profeIAP** [comment]
Perfecto, te ha quedado espectacular.
Gracias
