### ISSUE TITLE
Narrar cómo "soltar" una tarea que tenemos asignada en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#45]
Describir el proceso seguido en el vídeo de la tarea #44

**Comment by juankagb00** [comment]
https://drive.google.com/open?id=0BzGsa6imqpYJaXlRX2p5dmRMTDg

**Comment by juankagb00** [comment]
[Aquí el audio](https://drive.google.com/open?id=0BzGsa6imqpYJaXlRX2p5dmRMTDg)

**Comment by profeIAP** [comment]
No parecen coincidir los tiempos (amén de que el final es algo abrupto y queda como "a medias")
¿Utilizaste el vídeo mientras grababas la narración?

**Comment by juankagb00** [comment]
No, pero eso lo recorto y creo k coincide no? O lo hago denuevo?

**Comment by profeIAP** [comment]
No creo que logres hacerlo... te concedo el beneficio de la duda; como tienes asignada la tarea de "edición" (#129) prueba y vemos.

Si lo arreglas perfecto, si no, te tocará grabar nuevamente el audio ¿te parece?

**Comment by juankagb00** [comment]
Vale
