### ISSUE TITLE
Grabar cómo "enlazar" en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#46]
Crear un vídeo en el que se muestre cómo se puede enlazar cualquier dirección web dentro de los comentarios de GitHub.

Deberá incluirse la posibilidad de hacerlo:
1. utilizando el botón existente en el editor
1. utilizando directamente la sintaxis markdown

**Comment by AndreaRomero9** [comment]
Aqui tienes el [video]https://drive.google.com/file/d/0B-MuNBs4a49FSmpzVlRuZThwZlE/view?usp=sharing

**Comment by profeIAP** [comment]
Has equivocado el botón que se utiliza para enlazar XO

**Comment by profeIAP** [comment]
Igualmente oculta el enlace dentro del comentario anterior

**Comment by AndreaRomero9** [comment]
Aqui tienes el video `https://drive.google.com/file/d/0B-MuNBs4a49FSmpzVlRuZThwZlE/view?usp=sharing`

**Comment by AndreaRomero9** [comment]
Aqui tienes el video [https://drive.google.com/file/d/0B-MuNBs4a49FdllaRnI2ZlI4U2s/view?usp=sharing](url)

**Comment by profeIAP** [comment]
El enlace que aparece en el vídeo no puede funcionar en la vida (has puesto la url en la zona en la que debería estar el texto a enlazar dejando el espacio para la url sin la dirección web)

Igualmente, sigues sin ocultar enlaces en los comentarios anteriores. 

Que conste en "acta" que mientras no desaparezcan no daré por finalizada la tarea :)

**Comment by AndreaRomero9** [comment]
Aqui tienes [el video](uhttps://drive.google.com/open?id=0B-MuNBs4a49FdllaRnI2ZlI4U2)

**Comment by AndreaRomero9** [comment]
Aqui tienes [el video](https://drive.google.com/open?id=0B-MuNBs4a49FdllaRnI2ZlI4U2surl)

**Comment by profeIAP** [comment]
El vídeo no está bien... por favor, corrígelo

**Comment by AndreaRomero9** [comment]
aqui tienes [el enlace](http://www.sevillafc.es/)

**Comment by AndreaRomero9** [comment]
Ya por fin aqui tienes [el video](https://drive.google.com/file/d/0B-MuNBs4a49FUEZ0bkJMWXVRbms/view?usp=sharing)

**Comment by profeIAP** [comment]
La verdad es que está infinitamente mejor peeeeeroooo... haces un lío tremendo borrando y pegando direcciones.
Agradecería que lo volvieses grabar y te recomendaría:

1. Selecciones el texto en el que quieres poner el enlace
1. Pulses el botón de enlazar

De este modo evitas tener que estar borrando y corrigiendo cosas (y se entenderá mejor). Si lo necesitas, te cuento cómo hacerlo en clase

**Comment by AndreaRomero9** [comment]
Aqui tienes [el video](https://drive.google.com/file/d/0B-MuNBs4a49FOHlnZzd6Q054a00/view?usp=sharing), espero QUE NO TENGA QUE VOLVER HACERLO!!!!!!!!!!!

**Comment by profeIAP** [comment]
Pues te diría que habría quedado muchísimo mejor si hubieses pinchado en la vista previa 😂
No te obligaré a dejarlo perfecto pero sí a ocultar enlaces como acordamos 😜

**Comment by AndreaRomero9** [comment]
aqui tienes [el videeeoooo ](http://www.sevillafc.es/)

**Comment by AndreaRomero9** [comment]
aqui tienes [el enlaceeeeee](http://www.sevillafc.es/)

**Comment by profeIAP** [comment]
Ahora sí, muy buen trabajo Andrea.
