### ISSUE TITLE
Grabar cómo evitar notificaciones de GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#50]
Crear un vídeo en el que se muestre cómo evitar ser bombardeados con notificaciones en nuestro correo electrónico cada vez que alguien comenta algo en la web del proyecto

**Comment by alemorales1999** [comment]
por correo te he mandado el video

**Comment by profeIAP** [comment]
Y te ha quedado muy bien... ¡Buen trabajo!

¿Has observado la cantidad de ruido que tiene el vídeo?

Necesito:

1. Elimines el ruído
1. Quites la parte final del vídeo (en la que se ve cómo paras RecordMyDesktop)
1. Lo subas a [la carpeta que os he compartido](https://drive.google.com/drive/folders/0B1or4uFFvPJ-QkRqNlMxY0xta3c?usp=sharing) en Drive (hemos tenido suerte y el vídeo ocupa poco pero no siempre será así: mejor acostrumbrarnos a usar la carpeta para todo ¿no te parece?)

**Comment by alemorales1999** [comment]
https://drive.google.com/open?id=0B42JQKLr8bXaWm9FckwwbVBQODA ya está terminado

**Comment by profeIAP** [comment]
¿¡¿Por qué lo has grabado a 480p en lugar de a 720p como el resto de compañeros?!?
Igualmente necesito que ocultes los enlaces dentro de los comentarios para dar por cerrada la tarea.

**Comment by alemorales1999** [comment]
[lo de grabarlo  a 480p no me he dado cuenta](https://drive.google.com/open?id=0B42JQKLr8bXaWm9FckwwbVBQODA)

**Comment by profeIAP** [comment]
No te preocupes, el récord lo tiene @Frangamboag que ¡¡¡lo ha hecho a 360p!!!

![](https://cloud.githubusercontent.com/assets/16881846/19985805/a9e77712-a214-11e6-84f8-b541e8b139ba.jpg)

**Comment by profeIAP** [comment]
Por cierto, te quedan enlaces por ocultar en los primeros comentario de esta tarea.

**Comment by alemorales1999** [comment]
[ya está con la calidad que hace falta creo](https://drive.google.com/open?id=0B42JQKLr8bXaa1NLUlhkZTJpS3M)

**Comment by profeIAP** [comment]
Efectivamente, ahora está perfecto.
Gracias Alejandro
