### ISSUE TITLE
Narrar cómo evitar las notificaciones de GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#51]
Describir el proceso seguido en el vídeo de la tarea #50

**Comment by profeIAP** [comment]
Siento quitarte la tarea @alexandrabr00 pero la tarea la tenía asignada antes @claramartin29

**Comment by claramartin29** [comment]
Ya está hecha la [tarea](https://drive.google.com/open?id=0B3_UAgSTOs3ncFQ1MnN1blpKOUE)

**Comment by profeIAP** [comment]
Qué bien te ha quedado, ¡Enhorabuena!
