### ISSUE TITLE
Grabar cómo eliminar el audio de un vídeo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#52]
Crear un vídeo en el que se muestre cómo eliminar completamente la narración de un vídeo (quedándonos únicamente con las imágenes sin sonido)

Nos será de gran utilidad si tenemos que corregir algún fallo y hemos perdido los ficheros "originales"

**Comment by profeIAP** [comment]
@JoseManueh dice el refranero que quien llega tarde ni oye misa ni como "carne".

Observa que la tarea la tiene asignada @angel2190, te doy de "baja"

**Comment by angel2190** [comment]
listo aqui tienes el enlace
[https://drive.google.com/open?id=0B2gGs9Sfg8hbcndKZko1OG5mREk](url)

**Comment by angel2190** [comment]
listo aqui tienes el enlace
https://drive.google.com/open?id=0B2gGs9Sfg8hbcndKZko1OG5mREk

**Comment by profeIAP** [comment]
Está perfecto Ángel pero, para que te dé "coraje":

1. te voy a abrir la tarea
1. te voy a poner un 9 (en lugar del 10 que te mereces)

ya que necesito/quiero que los enlaces estén ocultos en los comentarios :P

**Comment by angel2190** [comment]
ya esta oculto?

**Comment by profeIAP** [comment]
Me temo que no... yo lo sigo viendo [en el siguiente comentario](https://github.com/profeIAP/Documentacion/issues/52#issuecomment-271272177)

**Comment by profeIAP** [comment]
Al final se ocultó, gracias Ángel
