### ISSUE TITLE
Grabar cómo hacer una captura de pantalla en nuestro ordenador

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#54]
Crear un vídeo en el que se muestre cómo se hace una captura de pantalla (o "screenshot") en Guadalinex.

**Comment by illanes16** [comment]
[https://drive.google.com/file/d/0B_NCVxOSdbWjU3hVQnhCWHZLMWM/view](url)

**Comment by illanes16** [comment]
[https://drive.google.com/open?id=0B_NCVxOSdbWjU3hVQnhCWHZLMWM](url)

**Comment by illanes16** [comment]
https://drive.google.com/open?id=0B_NCVxOSdbWjU3hVQnhCWHZLMWM

**Comment by illanes16** [comment]
cierro esta tarea #55

**Comment by profeIAP** [comment]
Te ha quedado muy bien Sergio pero recuerda:

1.  El vídeo incluye en el nombre "screencast" cuando estamos ante un "screenshot"
1. No has ocultado el enlace en el comentario de arriba (vimos cómo se hacía en clase)

**Comment by elenashp** [comment]
le asigno esto a Alicia Valle mientras espera que le acepten entrar en su cuenta

**Comment by laury11** [comment]
le asigno esta tarea a alicia valle hasta que pueda entrar en su cuenta.

**Comment by profeIAP** [comment]
Ni @elenashp ni @Sanchez18 ni @laury11 

Esta tarea la tiene asignada @illanes16 desde hace bastante tiempo (de echo, [se la asigné yo](https://github.com/profeIAP/Documentacion/issues/54#event-892298247))

Entiendo que sois "novatos" en estas lides (@illanes16 ya es veterano pues lleva dos años usando GitHub) por lo que no os lo tendré en cuenta 😏

Leed, mirad y preguntar si tenéis dudas... poco a poco os convertiréis en expertos en esta herramienta, tranquilos ;)

**Comment by illanes16** [comment]
aqui esta el [video](https://drive.google.com/open?id=0B_NCVxOSdbWjU3hVQnhCWHZLMWM) y cierro esta tarea #55

**Comment by profeIAP** [comment]
Peeerrooo... sigues sin cumplir lo pedido en [mi último comentario](https://github.com/profeIAP/Documentacion/issues/54#issuecomment-271892368) 😒

**Comment by illanes16** [comment]
[este es el video del screenshot](https://drive.google.com/file/d/0B_NCVxOSdbWjU3hVQnhCWHZLMWM/view)

**Comment by profeIAP** [comment]
Perfecto Sergio, muchas gracias
