### ISSUE TITLE
Grabar cómo cerrar la sesión en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#57]
Crear un vídeo en el que se muestre cómo se cierra la sesión que ha dejado un usuario abierta en GitHub

**Comment by Carjop** [comment]
Enlazado[](https://drive.google.com/open?id=0B8tTRlqZUkjndkdhbUNsRUZwZVk)

**Comment by profeIAP** [comment]
¿Dónde lo has enlazado? (porque en la tarea no está XD)

**Comment by elenashp** [comment]
le asigno esto a sofialg mientras espera que le acepten entrar en su cuenta

**Comment by Carjop** [comment]
https://drive.google.com/open?id=0B8tTRlqZUkjndkdhbUNsRUZwZVk

**Comment by profeIAP** [comment]
Oculta el enlace @Carjop para poder dar por cerrada la tarea.

@elenashp agradezo los comentarios (pues así te he pedido que lo hagas para que quedase claro por qué tenías varias tareas asignadas) pero ten en cuenta que para poder reservar realmente la tarea, debes usar el apartado de las "asignaciones" que aparece en el lado derecho

![captura de pantalla de 2017-01-12 18-17-01](https://cloud.githubusercontent.com/assets/16881846/21900240/66eb198a-d8f3-11e6-91a7-3c1f6349d811.jpg)

**Comment by Carjop** [comment]
https://drive.google.com/open?id=0B8tTRlqZUkjndkdhbUNsRUZwZVk

**Comment by profeIAP** [comment]
Oculta ese enlace que se le ven las "vergüenzas" y queda "feo"

**Comment by profeIAP** [comment]
Para dar por finalizada la tarea, oculta ese enlace que se le ven las "vergüenzas" y queda "feo" :P

**Comment by Carjop** [comment]
[Vídeo](https://drive.google.com/open?id=0B8tTRlqZUkjndkdhbUNsRUZwZVk)

**Comment by profeIAP** [comment]
Genial Carlos, muchas gracias
