### ISSUE TITLE
Grabar cómo eliminar claves almacenadas en el navegador

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#59]
Crear un vídeo en el que se muestre cómo se evita que el navegador tenga guardadas ciertas contraseñas (y que aparezcan automáticamente cuando se acceda a la página)

**Comment by profeIAP** [comment]
Si no sabes cómo hacerlo, te puede ser de utilidad [el siguiente artículo](https://andalinux.wordpress.com/2008/12/02/evitar-que-firefox-recuerde-determinada-contrasena/)

**Comment by elenashp** [comment]
le asigno esta tarea a Alicia Valle mientras espera que le acepten entrar en su cuenta.

**Comment by aliciavalle15** [comment]
Aquí tienes [el video ](https://drive.google.com/file/d/0BytR8hopIxdmYkJyNGRvSmlFRFE/view?usp=sharing)

**Comment by profeIAP** [comment]
Te ha quedado genial, ¡Gracias Alicia!

**Comment by profeIAP** [comment]
Aunque al final, imagino que por los nervios, terminas más rápido que el vídeo (le va tocar arreglarlo al que edite el vídeo y monte el trabajo) te ha quedado espectacularmente bien.

Muy buen trabajo, ¡enhorabuena Alicia!
