### ISSUE TITLE
Grabar cómo compartir una carpeta en Guadalinex

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#6]
Crear un vídeo en el que se muestre cómo se comparte una carpeta de nuestro ordenador con Guadalinex.

**NOTA**: Supondremos que samba está correctamente instalado (no hace falta documentar cómo se instala el script), sólo tienes que grabar la creación de la carpeta y su compartición.

**Comment by maria99mh** [comment]
Aquí tienes [el vídeo](https://drive.google.com/file/d/0BxEbuEKZS9TMVHZNZ0F5M3pidEk/view?usp=sharing)

**Comment by profeIAP** [comment]
Perfecto María, muy buen trabajo, gracias.
