### ISSUE TITLE
Narrar cómo iniciar la "navegación privada" en el navegador

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#62]
Describir el proceso seguido en el vídeo de la tarea #61

**Comment by profeIAP** [comment]
@albertvm10 te quito la tarea porque la tenía cogida @maricarmen01

**Comment by maricarmen01** [comment]
Ya está hecha la [tarea](https://drive.google.com/open?id=0BzuXr9g-7qn3NEotM3FocWlQYmc)

**Comment by profeIAP** [comment]
Espectacular, te ha quedado muy bien.
¡Enhorabuena!
