### ISSUE TITLE
Grabar cómo desactivar el modo avión en el portátil

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#65]
Crear un vídeo en el que se muestre cómo desactivar el "modo avión" del portátil que impide en más ocasiones de lo deseable poder conectarse a la red

**Comment by Sanchez18** [comment]
Hola maestro, aquí te dejo la grabacion de [como desactivar el modo avion](https://drive.google.com/open?id=0B2k3fjTlaE7GZ1JnM0RSUnZaSmM)

**Comment by profeIAP** [comment]
Gracias Dani pero ¿por qué lo has grabado a 480p? (se ve excesivamente pequeño ¿no te parece?)
Ya que tendrás que volverlo a grabar, agradecería que mostrases los cambios que se producen (antes y depués de desactivar el modo avión) en el applet de red.

Independientemente del tamaño está muy bien, no creo que te cueste demasiado volverlo a grabar en "cinemascope"

**Comment by Sanchez18** [comment]
Aquí te dejo el video cambiado  de [como desactivar el modo avion](https://drive.google.com/open?id=0B2k3fjTlaE7GLTNEVV9VSy1NeW8)

**Comment by profeIAP** [comment]
Genial Daniel, ha quedado genial.
Muchas gracias
