### ISSUE TITLE
Grabar cómo actualizar Firefox en Guadalinex

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#67]
Crear un vídeo en el que se muestre cómo actualizar el navegador Firefox que tenemos en el portátil a una versión más reciente.

Sería interesante que en el vídeo apareciesen las versiones inicial (el que tenemos actualmente) y la que hemos instalado.

Para aprender cómo se hace, te recomiendo [consultar el siguiente artículo](https://andalinux.wordpress.com/2016/10/18/tic-actualizar-firefox-en-guadalinex/)

**Comment by JaviierM** [comment]
[Video](https://drive.google.com/file/d/0BwgGhI4YeYIVeWJMNmVlc3pjZlk/view?usp=sharing)

**Comment by profeIAP** [comment]
Lo siento pero la solución que muestras es un "tongo":

1. Funciona porque el icono que tienes en el panel superior apunta a la versión actualizada de Firefox que alguien habrá instalado antes
1. No tiene sentido dar permisos de ejecución a un fichero comprimido
1. Abres el archivo comprimido única y exclusivamente para que se vea su contenido (no porque lo vayas a descomprimir que, por otra parte, es un requisito)
1. No se ve por ningún sitio que sea interesante ocultar la carpeta (poniendo un punto delante del nombre)
1. No se ve cómo se crea el supuesto lanzador del panel superior que usas para lanzarlo.

Por desgracia, son tantos los "peros" que considero que lo más sencillo será grabarlo de nuevo ;)

Ánimo Javier, verás como la próxima te sale bien

**Comment by JaviierM** [comment]
[Video](https://drive.google.com/file/d/0BwgGhI4YeYIVeWJMNmVlc3pjZlk/view?usp=sharing)

**Comment by profeIAP** [comment]
Los enlaces de los comentarios anteriores deben estar ocultos para dar por buena la tarea.

No obstante lo que has grabado no termina de estar bien:

1. No tiene sentido dar permiso de ejecución a un fichero comprimido
1. Tras descomprimir el fichero haces click en uno de los accesos directos que **ya tenías** en tu panel superior (todo lo que has grabado antes no tiene sentido)

Deberías:

1. Acceder al directorio donde descomprimes el fichero
1. Crear el acceso directo
1. Demostrar que funciona

**Comment by JaviierM** [comment]
[video](https://drive.google.com/file/d/0BwgGhI4YeYIVdWs0REJaQklOVXJkYjVCWWp6Z0tLUjRkZVFn/view?usp=sharing)

**Comment by profeIAP** [comment]
Fantástico Javier, gran trabajo (gracias)
Sólo necesito que ocultes **todos** los enlaces de los comentarios que has ido realizando para poder dar por cerrada la tarea.
¡Enhorabuena!

**Comment by JaviierM** [comment]
https://drive.google.com/file/d/0BwgGhI4YeYIVdWs0REJaQklOVXJkYjVCWWp6Z0tLUjRkZVFn/view?usp=sharing
[video](url)

**Comment by JaviierM** [comment]
[Video](https://drive.google.com/file/d/0BwgGhI4YeYIVdWs0REJaQklOVXJkYjVCWWp6Z0tLUjRkZVFn/view?usp=sharing)

**Comment by JaviierM** [comment]
[grabación](https://drive.google.com/file/d/0BwgGhI4YeYIVZ0ZsclJIbzRoQ0k/view?usp=sharing``)

**Comment by profeIAP** [comment]
Gracias por ocultar los enlaces Javier, buen trabajo.
Me surge una duda... ¿por qué te ha dado por enlazar dos vídeos más en los últimos comentarios? 😳

**Comment by JaviierM** [comment]
Un fue por error, y la otra porque me asigné otra y se me olvidó quitarla😅

**Comment by profeIAP** [comment]
Ocurre en las mejores familias, no te preocupes.
Buen trabajo, Javi
