### ISSUE TITLE
Narrar cómo actualizar Firefox en Guadalinex

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#68]
Describir el proceso seguido en el vídeo de la tarea #67

**Comment by JaviierM** [comment]
[Narración](https://drive.google.com/open?id=0BwgGhI4YeYIVZ0ZsclJIbzRoQ0k)

**Comment by profeIAP** [comment]
Te ha quedado genial Javier, enhorabuena.
Igual que con el vídeo, exigiré se cumpla con la "ocultación de enlaces" para poder dar por finalizada la tarea ;)
