### ISSUE TITLE
Grabar cómo mostrar un selector de fechas en Google Sheets

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#69]
Crear un vídeo en el que se muestre [cómo incluir un calendario para la selección de una fecha](https://andalinux.wordpress.com/2016/04/05/selectores-de-fecha-en-las-hojas-de-calculo-de-google-drive/) en cualquier celda de Google Sheets (hoja de cálculo de Drive)

**Comment by SantiagoJiBe** [comment]
Maestro, aquí tienes [el video](https://drive.google.com/open?id=0BxHuCXCBd50vVHFUQnNLdllpWDA)

**Comment by profeIAP** [comment]
Te ha quedado genial, muchas gracias Santi
