### ISSUE TITLE
Grabar cómo compartir una carpeta en Windows XP

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#7]
Crear un vídeo en el que se muestre cómo se crea y comparte una carpeta en un ordenador con Windows XP

**NOTA 1:** No debe verse la máquina virtual; debe parecer que realmente se está utilizando WinXP (puedes usar la vista a pantalla completa de Virtual Box o bien probar la herramienta que trae VirtualBox para grabar vídeo)

**NOTA 2:** La etiqueto como "reto" al requerir cierta investigación (y pruebas) encontrar el modo más adecuado de grabar el vídeo sin que se note que estamos usando una máquina virtual.

**NOTA 3:** Utiliza una máquina virtual de WinXP en la que al compartir se vea que hay que elegir un enlace y configurar (utilizando el asistente) la compartición 

![](http://www.iesromerovargas.com/recursos/elec/sol/Compartir%20carpetas%20Windows%20XP%20Uso%20compartido%20simple%20de%20archivos_archivos/13compartir0.gif)

y no directamente el "tic" para activarla

![](http://3.bp.blogspot.com/-5a3BFhl3ubQ/TcQsFb2PWCI/AAAAAAAAAA4/5Z0Aae-9224/s1600/compartirarchivos.png)

**Comment by gabrircurz** [comment]
Enlazado[](https://drive.google.com/open?id=0BwusAkelVplkTW5NdUQ5Wi1nUlE)

**Comment by profeIAP** [comment]
Pero se ha olvidado el enlace ;)
Cuando lo pongas, recuerda cerrar la tarea, gracias.

**Comment by AliciaValle** [comment]
https://drive.google.com/open?id=0BwusAkelVplkTW5NdUQ5Wi1nUlE

**Comment by gabrircurz** [comment]
https://drive.google.com/open?id=0BwusAkelVplkTW5NdUQ5Wi1nUlE

**Comment by profeIAP** [comment]
De lujo Gabriel, muy buen trabajo. ¡Enhorabuena!
