### ISSUE TITLE
Narrar cómo mostrar un selector de fechas en Google Sheets

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#70]
Describir el proceso seguido en el vídeo de la tarea #69

**Comment by SantiagoJiBe** [comment]
aqui tienes el [enlace](https://drive.google.com/drive/folders/0B1or4uFFvPJ-U2c4RGVpMUNPSU0)

**Comment by SantiagoJiBe** [comment]
aqui tienes el [enlace](https://drive.google.com/open?id=0BxHuCXCBd50veHJiT3pSTHhONEk)

**Comment by profeIAP** [comment]
Te ha quedado muy bien Santi pero se me escucha hasta a mi de fondo y se hace un suplicio oirte con tanto ruído 😳
Podrías intentar reducir el ruído con Audacity pero sospecho que te costará "menos" narrarlo de nuevo

**Comment by SantiagoJiBe** [comment]
vale, @profeIAP a ver que te parece [este](https://drive.google.com/open?id=0BxHuCXCBd50vMEUtaEQ2WWRkUzA)

**Comment by profeIAP** [comment]
Fantástico, muchísimas gracias Santi
