### ISSUE TITLE
Grabar cómo listar las tareas asignadas a un usuario en Github

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#71]
Crear un vídeo en el que se muestre [cómo ver las tareas que tiene asignadas cierta persona en Github](https://andalinux.wordpress.com/2016/03/22/listar-las-tareas-asignadas-en-github/).

**Comment by balbuenafj** [comment]
aqui te pongo el enlace a [mi grabación](https://drive.google.com/open?id=0B_3KDLMb1fCmME1DdWxrTHJfMEEl), subida a google drive solamente me faltaria grabar la narración un saludo¡¡¡

**Comment by balbuenafj** [comment]
en el primer enlace no lleva a ninguna parte perdona, aora creo que este si lleva al [sitio,](https://drive.google.com/open?id=0B_3KDLMb1fCmME1DdWxrTHJfMEE)

**Comment by profeIAP** [comment]
No te preocupes Francisco, estás empezando.

El vídeo no coincide con el objetivo de la tarea; me explico: se pide listar las taras asignadas a un usuario concreto y has grabado aquellas que están sin asignar (=libres)

**Comment by balbuenafj** [comment]
Claro es lo que te comente en clase..

**Comment by profeIAP** [comment]
Ya me extrañaba... no había mirado la fecha de cuándo habías subido el enlace.
Disculpa las molestias.

**Comment by balbuenafj** [comment]
Sin ningún problema feliz finde semana!!!

**Comment by balbuenafj** [comment]
[este video es el  bueno puede ser el bueno](https://drive.google.com/open?id=0B_3KDLMb1fCmWjVlRmxMbU4yckk)

**Comment by profeIAP** [comment]
Te ha quedado genial, ¡enhorabuena Balbuena!
