### ISSUE TITLE
Grabar cómo obtener las tareas que están "libres" en Github

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#73]
Crear un vídeo en el que se muestre cómo listar todas las tareas que no tiene asignadas nadie.

![captura de pantalla de 2017-01-09 18-43-18](https://cloud.githubusercontent.com/assets/16881846/21776598/97fca43a-d69b-11e6-9847-99175ef561d3.png)

**Comment by marinaca7** [comment]
Ya he terminado el video, corrigelo. 
https://drive.google.com/drive/folders/0B1or4uFFvPJ-SVljVTNyQ25RRWM

**Comment by profeIAP** [comment]
Aunque al principio es algo "brusco" el comienzo (vas directamente a la lista desplegable de asingaciones en Github) te ha quedado muy bien.

Gracias Marina.

**NOTA:** en esta ocasión me voy a "invitar" yo pero, la próxima vez, recuerda pulsar el botón "Cerrar tarea" ¿ok? 😉
