### ISSUE TITLE
Narrar cómo obtener las tareas que están "libres" en Github

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#74]
Describir el proceso seguido en el vídeo de la tarea #73

**Comment by albaag20** [comment]
hecho[https://drive.google.com/file/d/0B7VbTuFV9GGEb0ZSM1YweDhyMTA/view?usp=sharing](url)

**Comment by profeIAP** [comment]
Te ha quedado perfecto.
Muy clarito y sin apenas ruido.
Muy buen trabajo, gracias.
