### ISSUE TITLE
Grabar cómo hacer olvidar la clave wifi en Guadalinex

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#75]
Crear un vídeo en el que se muestre cómo impedir que Guadalinex intente utilizar la última clave introducida para alumnado-alandalus

**Comment by Miguelcaspor** [comment]
[Aqui tienes el video](https://drive.google.com/file/d/0BxSmuoeOhbYoUlBKdWh6N2x6eDA/view?usp=sharing)

**Comment by profeIAP** [comment]
Recuerda ocultar el enlace para dar por cerrada la tarea.

Hubiese estado bien Miguel ver qué, cuando seleccionas la wifi que has borrado, te pide la clave.

De todos modos queda muy bien, déjalo asi... ¡Buen trabajo!

**Comment by profeIAP** [comment]
Reabro la tarea pues no se cerrará hasta que el enlace quede oculto ;)

**Comment by Miguelcaspor** [comment]
El enlace ya esta ocultado para que me lo evalues ;)

**Comment by profeIAP** [comment]
Di que sí... casi ni lo encuentro de oculto que está XP
Buen trabajo Miguel, gracias
