### ISSUE TITLE
Grabar cómo obtener la dirección MAC en Windows

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#77]
Crear un vídeo en el que se muestre [cómo obtener la dirección MAC de la tarjeta de red en un equipo con Windows](https://andalinux.wordpress.com/2015/09/23/obtener-direccion-mac-en-windows/).

**NOTA:** se etiqueta como _reto_ al requerir su grabación usar la máquina virtual con WinXP que tenemos en clase

**Comment by daniveg20** [comment]
Hola maestro, aquí tienes el enlace de la grabación de [cómo obtener la dirección MAC](https://drive.google.com/open?id=0B7Bi54VPufr-MzJ5SnM3ZGF1TVE)

**Comment by profeIAP** [comment]
Ha quedado genial pero me ha sorprendido que se pueda pegar el parámetro (en tu caso /all) al comando (ipconfig) 😳

Lo que me ha gustado un poco menos es que se vea el "truco" de estar usando una máquina virtual ¿costaría mucho volver a grabarlo? 😇

**Comment by daniveg20** [comment]
Hola maestro, aquí tienes el enlace de la grabación de[ cómo obtener la dirección MAC ](https://drive.google.com/open?id=0B7Bi54VPufr-MzJ5SnM3ZGF1TVE
)

**Comment by profeIAP** [comment]
Muchísimas gracias, ha quedado perfecto Dani
