### ISSUE TITLE
Narrar cómo obtener la dirección MAC en Windows

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#78]
Describir el proceso seguido en el vídeo de la tarea #77

**Comment by daniveg20** [comment]
Hola maestro, aquí tienes el enlace de la narración de [cómo obtener la dirección MAC](https://drive.google.com/open?id=0B7Bi54VPufr-bjJOcXF3SS1NVzg)

**Comment by profeIAP** [comment]
Aunque algo nervioso (normal) te ha quedado muy bien Daniel, gracias.

Le voy a poner una pega (en caso contrario no me quedaría tranquilo 😏) y es que el comando CMD no tiene por qué aparecer al pulsar Win+R (en tu caso aparece porque fue el último comando ejecutado)

No te preocupes: basta con grabar un trocito indicando que se debe escribir CMD (viene de **C**o**M**man**D**) para acceder a la terminal y ya lo pegaremos al resto del fichero de sonido que tienes grabado (usando Audacity)

**Comment by daniveg20** [comment]
Hola maestro, aquí tienes el enlace de la narración de [cómo obtener la dirección MAC](https://drive.google.com/open?id=0B7Bi54VPufr-bjJOcXF3SS1NVzg)

**Comment by profeIAP** [comment]
Te ha quedado genial Daniel, gracias por tratar de seguir siendo "perfeccionista" a pesar de los nervios ;)

Observo que la tarea de edición del vídeo y el audio que has grabado no está asignado a nadie. Si sigue estando libre, sería interesante que la cogieses (en lugar del código QR que tenienes actualmente #242) para tratar de solventar el espacio (sin vídeo) que queda cuando te estás "despidiendo" en la narración ;)

Sólo es una sugerencia
