### ISSUE TITLE
Grabar cómo desactivar la wifi en Guadalinex

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#79]
Crear un vídeo en el que se muestre cómo evitar que salte continuamente la wifi (si en la grabación aparece el molesto mensaje pidiendo la clave de la wifi cuando estás conectado por cable, mejor que mejor) desactivando la conexión wifi desde el applet de red
![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTBngrZXvTRqzZJcymOrDCsliz7bDeX7F74BepMRWoeEO86mSZo)

**Comment by gloocc8** [comment]
mi video https://drive.google.com/open?id=0B-2fXC6wcqz6SV9TN243bzV6bHc

**Comment by profeIAP** [comment]
Perfecto Rocío (gracias) pero, para dar por finalizada la tarea, deberás ocultar el enlace que has puesto en tu comentario anterior

**Comment by profeIAP** [comment]
**NOTA:** no olvides cerrar la tarea cuando lo ocultes

**Comment by profeIAP** [comment]
Ha quedado muy clarito, enhorabuena Gloria.
La única pena es que no has capturado la molesta solicitud de contraseña de wifi :(
