### ISSUE TITLE
Grabar cómo acceder a las herramientas multimedia

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#8]
Una vez instalados (no debe aparecer en el vídeo cómo se instalan) en tu equipo los siguientes programas:
+ RecordMyDesktop (para hacer screencasting de nuestra pantalla)
+ PiTiVi (para componer nuestros vídeos)
+ Audacity (para realizar las grabaciones y editar las pistas de audio)

deberás crear un vídeo en el que se muestre dónde se encuentran estos programas en el menú de aplicaciones

**Comment by 14Josegar** [comment]
TAREA [HECHA](https://drive.google.com/file/d/0B3vShWbEwiu-eFY3d2cwcFlsSXc/view?usp=sharing)

**Comment by profeIAP** [comment]
Pues tenías razón... ya lo habías subido ¿?

De todos modos, en el vídeo sólo aparece la ubicación de PiTiVi y recordMyDesktop (pero no Audacity que es el que está más escondido)

Personalmente considero que no es necesario abrir PiTiVi (tampoco se pide en la descripción de la tarea)

Te recomendaría abrir la opción de menú Aplicaciones > Sonido y Vídeo y dejar unos segundos para que a tus compañeros le dé tiempo a ver los programas (eres excesivamente rápido)

Confío que las "enseñanzas" de @Frangamboag te hayan servido para poder hacerlo nuevamente 😒

**Comment by 14Josegar** [comment]
TAREA HECHA DE NUEVO https://drive.google.com/open?id=0B3vShWbEwiu-TEJpVHJTenN5amM

**Comment by profeIAP** [comment]
Espectacular Jose, muchas gracias por tomarte la molestia.
Para finalizar:
1. Oculta el enlace anterior
1. Cierra la tarea (con el botón que existe para tal fin)
Mi enhorabuena.

**Comment by profeIAP** [comment]
Ahora sí, un trabajo muy fino.
Gracias Jose

**Comment by profeIAP** [comment]
Te ha quedado muy simpático Gloria pero no está "limpio" y titubeas un poco.
Creo que sería mejor volver a grabarlo pero lo dejo a tu elección 😏
Si quieres, lo hablamos

**Comment by profeIAP** [comment]
Me confundí de tarea, la vuelvo a cerrar pues estaba bien.
