### ISSUE TITLE
Grabar cómo instalar un plugin en Gimp

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#83]
Crear un vídeo en el que se muestre [cómo instalar un plugin en Gimp](https://andalinux.wordpress.com/2013/08/26/dibujar-flechas-con-gimp/)

**Comment by elenashp** [comment]
Asigno esta tarea a Sofía López Gallego mientras espera que le acepten entrar en su cuenta.

**Comment by sofialg** [comment]
Aquí tienes [los dos vídeos.](https://drive.google.com/file/d/0ByX9-8bPmeb4VHQtQ1FQczJ3UU0/view?usp=sharing)[](https://drive.google.com/file/d/0ByX9-8bPmeb4VHQtQ1FQczJ3UU0/view?usp=sharing)

**Comment by sofialg** [comment]
Aquí tienes el [primer](https://drive.google.com/file/d/0ByX9-8bPmeb4WHdXUnJIdmVWWTQ/view?usp=sharing) y [segundo](https://drive.google.com/file/d/0ByX9-8bPmeb4VHQtQ1FQczJ3UU0/view?usp=sharing) vídeo.

**Comment by profeIAP** [comment]
Perfecto Sofia, muy buen trabajo, gracias.
