### ISSUE TITLE
Narrar cómo instalar un plugin en Gimp

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#84]
Describir el proceso seguido en el vídeo de la tarea #83

**Comment by elenashp** [comment]
Asigno esta tarea a Sofía López Gallego mientras espera que le acepten entrar en su cuenta.

**Comment by sofialg** [comment]
Maestro, aquí tienes el [audio](https://drive.google.com/file/d/0ByX9-8bPmeb4RG52ZExRdGRZczg/view?usp=sharing) primer vídeo y el [segundo audio](https://drive.google.com/file/d/0ByX9-8bPmeb4THNkb3prZHFtUEU/view?usp=sharing) del otro vídeo.

**Comment by profeIAP** [comment]
¿¡¿Realmente eres tú @sofialg la que está narrando?!?

El audio va algo acelerado y cuesta sincronizarlo con el vídeo que se está viendo... vamos a tener que hablarlo y/o mejorarlo

**Comment by sofialg** [comment]
jjaja claro quien va a ser si no, mira el problema es que puede que no se
me entienda en algunas palabras demasiado bien, ya que el dentista me puso
un aparato en el cielo de la boca y me cuesta vocalizar todo correctamente
y me cuesta hablar aunque ya lo llevo algo mejor. Seguramente sea eso y
además por audio mi voz se transforma por completo, cuando quiera lo
comprobamos, vaya que no te estoy engañando ni mucho menos.

**Comment by profeIAP** [comment]
No es necesario comprobarlo, entiendo que es complicado acostumbrarse a la nueva situación :)
Doy por finalizada la tarea

**Comment by sofialg** [comment]
Gracias, de todas formas mañana lo hablamos si deseas mejor para aclararlo
todo
