### ISSUE TITLE
Grabar cómo identificar cualquier imagen usando Google Images

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#85]
Crear un vídeo en el que se muestre [cómo reconocer cualquier imagen y/u objeto que aparece en una fotografía utilizando Google Images](https://andalinux.wordpress.com/2014/04/29/vago-no-preguntes-mas-por-el-wallpaper/)

**Comment by laury11** [comment]
Aquí tienes [el vídeo](https://drive.google.com/file/d/0B1S2PqrIzBDRV0dndEVsVGVuYmxnYmdublJjSnV4dDRBaFlr/view?usp=sharing)

**Comment by profeIAP** [comment]
Perfecto, Laura, muchas grácias.
Buen trabajo.
