### ISSUE TITLE
Narrar cómo identificar cualquier imagen usando Google Images

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#86]
Describir el proceso seguido en el vídeo de la tarea #85

**Comment by laury11** [comment]
Está [Hecho](https://drive.google.com/open?id=0B1S2PqrIzBDRRUNzOXJSeWZlc00)

**Comment by profeIAP** [comment]
Lo siento Laura, apenas se te oye (ni siquiera subiendo el volumen por encima de lo saludablemente aconsejable)

**Comment by laury11** [comment]
Está [hecho](https://drive.google.com/file/d/0B1S2PqrIzBDRbjVENGx1UVpJN0E/view?usp=sharing)

**Comment by profeIAP** [comment]
No dejas de sorprenderme, Laura ¡Enhorabuena!

Los tiempos no coinciden pero como la tarea #108 de edición la tienes asignada tú, daré por bueno el trabajo a falta de que me demuestres que eres capaz de "cuadrar" sonido y vídeo (te vas a "divertir" y, de paso, aprender la técnica 😂)

Esta tarea la dejo abierta esperando que **corrijas** las faltas de ortografía que hay en tus comentarios.
