### ISSUE TITLE
Grabar cómo aplicar OCR usando Google Drive

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#87]
Crear un vídeo en el que se muestre [cómo utilizar Google Drive para realizar un reconocimiento de caracteres (OCR)](https://andalinux.wordpress.com/2014/04/07/herramienta-ocr-online-google/)

**Comment by albertvm10** [comment]
Aqui tienes el [enlace](https://drive.google.com/drive/folders/0B1or4uFFvPJ-SVljVTNyQ25RRWM)

**Comment by profeIAP** [comment]
Lo siento Alberto, debe de estar genial el vídeo pero, te has confundido, y has mandado enlace a la carpeta en la que se encuentra y, para facilitar el trabajo del que tenga que usar tu grabación, es deseable que enlaces el fichero concreto evitándoles confusiones cuando tenga que hacer su parte 😉

**Comment by albertvm10** [comment]
aqui esta el [enlace](https://drive.google.com/open?id=0B2w8fNHSCgBqRWVRMnQ0S2FMRGc) corregido maestro

**Comment by profeIAP** [comment]
Qué ganas tenía de verlo, gracias Alberto.

Sólo hay algo que no parece quedar claro: se supone que subes una **imagen** que es la que abres como documento de texto.

Y en el vídeo, sólo se ve cómo abres el documento que has utilizado en pruebas anteriores 😓

**Comment by albertvm10** [comment]
[Aquí tienes el enlace nuevamente](https://drive.google.com/open?id=0B2w8fNHSCgBqRWVRMnQ0S2FMRGc)

**Comment by albertvm10** [comment]
el anteriror comentario no es el video,me he equivocado

**Comment by albertvm10** [comment]
este es [maestro](https://drive.google.com/open?id=0B2w8fNHSCgBqc3QxeWQybm5JMHc)

**Comment by profeIAP** [comment]
Espectacular Alberto, un gran trabajo del que sentirse orgulloso ¡Gracias!

Abro la tarea con la esperanza de ver cómo ocultas el enlace que has puesto en tu último comentario ;)

**Comment by albertvm10** [comment]
aquí esta el [enlace oculto](https://drive.google.com/open?id=0B2w8fNHSCgBqc3QxeWQybm5JMHc)

**Comment by profeIAP** [comment]
Pero no lo has ocultado en [el comentario que de dije](https://github.com/profeIAP/Documentacion/issues/87#issuecomment-279007028)... vuelvo a abrir para que lo dejes como es debido :)

**Comment by profeIAP** [comment]
Ahora sí, muy buen trabajo Alberto 
¡Gracias!
