### ISSUE TITLE
Grabar cómo eliminar un icono del panel de Guadalinex

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#89]
Crear un vídeo en el que se muestre cómo eliminar cualquier icono de aplicación que alguien haya dejado en el panel de nuestro Guadalinex (deberás tener pulsada la tecla _Alt_ al hacer click con el botón derecho del ratón)

![](http://2.bp.blogspot.com/-mAibBT4xCyI/T5qSTdvD8jI/AAAAAAAADuk/FxNKCVvtQbE/s1600/shortcut-icon-gnome-classic-top-bar-.png)

**Comment by mariateresapg01** [comment]
Listo!
Te dejo el enlace: https://drive.google.com/open?id=0B77IAfhm-w9pT3c4SnpfYnFISFU

**Comment by profeIAP** [comment]
El vídeo tiene problemas en la grabación.
Lo más probable es que no pueda solucionarse (de momento) en Guadalinex Next.
Te recomendaría grabarlo en el equipo de cualquiera de tus compañeros que tenga la versión anterior (sorry)

**Comment by profeIAP** [comment]
Por cierto, recuerda ocultar los enlaces en los comentarios (gracias)

**Comment by mariateresapg01** [comment]
Te dejo el enlace del vídeo grabado con otro ordenador.
https://drive.google.com/file/d/0B77IAfhm-w9pWTRycm9iZlhIQjVhWnVHaTdUYkhFZnh5d2FR/view?usp=drivesdk

**Comment by profeIAP** [comment]
Te ha quedado perfecto, gracias Teresa por tomarte la molestia de volver a grabarlo.
Para poder cerrar la tarea, necesito que ocultes los enlaces de tus comentarios anteriores :)

**Comment by mariateresapg01** [comment]
Okey

**Comment by mariateresapg01** [comment]
Te dejo el [enlace](https://drive.google.com/file/d/0B77IAfhm-w9pWTRycm9iZlhIQjVhWnVHaTdUYkhFZnh5d2FR/view?usp=drivesdk)

**Comment by profeIAP** [comment]
Perfecto, gracias
