### ISSUE TITLE
Grabar el cambio de NAT a "Adaptador puente" en una máquina virtual

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#9]
Crear un vídeo en el que se muestre cómo cambia la IP en la barra de estado 

![blog-mysql-1](https://cloud.githubusercontent.com/assets/16881846/20846660/026c9efe-b8cb-11e6-82f4-6b21a6af7161.png)

al cambiar la configuración de la tarjeta de red entre los dos modos indicados

**Comment by marielasan11** [comment]
Hola! 
El otro día estuve grabando el audio y el vídeo que pertenecen a esta tarea, ha habido un pequeño problemita y es que el vídeo queda muy corto y el audio demasiado largo. Hablé con el profesor y me dijo que pidiera si podría asignarme esta tarea yo, para poder encajar el audio y el vídeo de alguna forma.

**Comment by profeIAP** [comment]
Queda en manos de @Andreacasado, esperamos una decisión pues ella tiene la última palabra.

**Comment by marielasan11** [comment]
Me asigno esta tarea de @Andreacasado tras darme [permiso](https://github.com/profeIAP/Documentacion/issues/29#issuecomment-274904219) de ello

**Comment by marielasan11** [comment]
Aqui dejo el video en el cual se ve el [cambio](https://drive.google.com/open?id=0BwBwdkQMENfYWVJDQ0d1QmxtYlk) de NAT a adaptador puente

**Comment by profeIAP** [comment]
Damos por cerrada la tarea, está perfecta.
Buen trabajo
