### ISSUE TITLE
Grabar cómo iniciar modo navegación privada por defecto en Firefox

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#93]
Crear un vídeo en el que se muestre [cómo iniciar modo navegación privada por defecto en Firefox](https://andalinux.wordpress.com/2013/04/08/iniciar-en-modo-navegacion-privada-por-defecto/)

**Comment by FcoHumanessab** [comment]
Yo haré la tarea.

**Comment by FcoHumanessab** [comment]
En este enlace(https://drive.google.com/open?id=0B3GMW7GMWk9Mb21yWDE0eXh5QW8) está el video, maestro.

**Comment by profeIAP** [comment]
Gracias Fran, aunque no has seguido el modo explicado en el enlace que suministré en la descripción de la tarea, me ha gustado aprender una nueva forma de hacerlo (gracias)

Lo único que no me termina de convencecer es que no hayas grabado cómo se inicia en modo privado el navegador tras el cambio que has aplicado lo cual, junto al comentario que escribes en el editor de textos (muy propio de tutoriales en youtube XD), me hace "sospechar" 😒

Lo más sencillo sería grabar el fragmento que falta y ya se unirán en la edición final del vídeo ¿te parece factible?

Como requisito, agradecería ocultases el enlace al vídeo pues queda bastante "feo" que se vea.

**Comment by FcoHumanessab** [comment]
Aquí tienes el nuevo vídeo:https://drive.google.com/open?id=0B3GMW7GMWk9MbWZQTDFsMURSalE

**Comment by profeIAP** [comment]
Genial, muchas gracias D. Francisco.
Sólo echo de menos que se oculten los enlaces 😏
Es una pena que no tengas la última versión de Firefox: en ella se nota mejor que se ha iniciado el modo de navegación privada.

Para **finalizar** la tarea: 
1. oculte el enlace
1. pulse el botón "cerrar tarea"

Muy buen, y detallado trabajo, gracias Francisco

**Comment by profeIAP** [comment]
Perfecto, gracias
