### ISSUE TITLE
Narrar cómo iniciar modo navegación privada por defecto en Firefox

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#94]
Describir el proceso seguido en el vídeo de la tarea #93

**Comment by FcoHumanessab** [comment]
Aquí está el audio [https://drive.google.com/open?id=0B3GMW7GMWk9MQXljLWkxOUVGeUE](url)

**Comment by profeIAP** [comment]
Me ha encantado su grabación D. Fco. pero no he conseguido hacer coincidir audio y vídeo

**Comment by FcoHumanessab** [comment]
Nueva grabación:https://drive.google.com/open?id=0B3GMW7GMWk9MRlJQWUJEdGpmYUE

**Comment by profeIAP** [comment]
Incluyendo un poco de retraso al comienzo (ya le contaré "el truco") va a quedar genial.
Muy buen trabajo, gracias Francisco.

Lo **olvidaba**: recuerde ocultar el enlace y cerrar la tarea para darla por finalizada :)
