### ISSUE TITLE
Grabar cómo acortar direcciones web con goo.gl

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#97]
Crear un vídeo en el que se muestre cómo acortar cualquier dirección web [usando Goo.gl](https://goo.gl/)

**Comment by antonio3560** [comment]
La tarea la pedí yo antes... te la quito por si no lo has visto

**Comment by antonio3560** [comment]
enlace de como acortar una dirección.[enlace](https://drive.google.com/open?id=0B4WiMunlwJ5XbmZXSkV2ei1nQU0)

**Comment by profeIAP** [comment]
Genial Antonio, muy buen trabajo.
¡Gracias!
