### ISSUE TITLE
Grabar cómo recortar un fragmento de una imagen usando Gimp

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#99]
Crear un vídeo en el que se muestre cómo seleccionar una zona de una image usando la siguiente herramienta de Gimp

![captura de pantalla de 2017-01-09 20-07-16](https://cloud.githubusercontent.com/assets/16881846/21779303/59ab5d78-d6a7-11e6-93bf-d9d9d8cd0b51.jpg)

**Comment by profeIAP** [comment]
@elenashp ¿al final vas a hacer esta tarea?
Por liberarla para otra persona.
Gracias

**Comment by elenashp** [comment]
Aquí tiene [el vídeo](https://drive.google.com/file/d/0B836udDJlFJjNmZheXNLSG9jZ0E/view?usp=sharing)

**Comment by profeIAP** [comment]
Perfecto Elena, gracias
